(() => {
  "use strict";
  const CONFIG = { recallUrl: "data/recalls.json", demoRecallUrl: "data/demo-recalls.json", demoUrl: "data/demo-products.json", offUrl: "https://world.openfoodfacts.org/api/v2/product/", timeout: 9000, staleDays: 8 };
  const state = { recalls: null, demoRecalls: null, demos: [], scannerControls: null, stream: null, lastScan: "", pendingBarcode: "", lastFocus: null };
  const $ = (id) => document.getElementById(id);
  const el = (tag, text, className) => { const node = document.createElement(tag); if (text != null) node.textContent = text; if (className) node.className = className; return node; };

  function normalizeBarcode(value) { return String(value ?? "").replace(/[\s-]/g, "").replace(/[^0-9]/g, ""); }
  function isRecognizedLength(code) { return [8, 12, 13, 14].includes(normalizeBarcode(code).length); }
  function validateCheckDigit(value) {
    const code = normalizeBarcode(value); if (!isRecognizedLength(code)) return false;
    const digits = [...code].map(Number); const supplied = digits.pop();
    const sum = digits.reverse().reduce((total, digit, i) => total + digit * (i % 2 === 0 ? 3 : 1), 0);
    return (10 - (sum % 10)) % 10 === supplied;
  }
  function generateGtinVariants(value) {
    const code = normalizeBarcode(value); const variants = new Set([code]);
    if (code.length === 12) { variants.add(`0${code}`); variants.add(`00${code}`); }
    if (code.length === 13) { variants.add(`0${code}`); if (code.startsWith("0")) variants.add(code.slice(1)); }
    if (code.length === 14) { if (code.startsWith("0")) variants.add(code.slice(1)); if (code.startsWith("00")) variants.add(code.slice(2)); }
    return [...variants].filter(Boolean);
  }
  function normalizeText(value) { return String(value ?? "").normalize("NFKD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim(); }
  function normalizeBrand(value) { return normalizeText(value).replace(/\b(inc|llc|company|co)\b/g, "").replace(/\s+/g, " ").trim(); }
  function normalizePackageSize(value) { return normalizeText(value).replace(/\bounces?\b/g, "oz").replace(/\bpounds?\b/g, "lb").replace(/\s+/g, ""); }
  function exactCodeMatch(code, recall) { const variants = new Set(generateGtinVariants(code)); return [...(recall.upcs || []), ...(recall.gtins || [])].some(item => generateGtinVariants(item).some(v => variants.has(v))); }
  function productNameTokenComparison(a, b) { const ignored = new Set(["the", "and", "with", "food"]); const x = new Set(normalizeText(a).split(" ").filter(t => t.length > 2 && !ignored.has(t))); const y = new Set(normalizeText(b).split(" ").filter(t => t.length > 2 && !ignored.has(t))); if (!x.size || !y.size) return 0; return [...x].filter(t => y.has(t)).length / Math.min(x.size, y.size); }
  function scoreRecall(product, recall) {
    const raw = normalizeBarcode(product.code); const recallCodes = [...(recall.upcs || []), ...(recall.gtins || [])];
    const exact = recallCodes.some(code => normalizeBarcode(code) === raw);
    if (exactCodeMatch(product.code, recall)) return { score: 100, matchMethod: exact ? "exact_identifier" : "equivalent_gtin", matchedFields: [exact ? "barcode" : "equivalent GTIN"], exactBarcode: exact, equivalentBarcode: !exact, usedSimilarity: false, reason: `The ${exact ? "exact barcode" : "equivalent GTIN representation"} matches an identifier in the official record.` };
    const brand = (recall.brandNames || []).some(b => normalizeBrand(b) === normalizeBrand(product.brands));
    const name = Math.max(0, ...(recall.productNames || []).map(n => productNameTokenComparison(product.product_name, n)));
    const size = (recall.packageSizes || []).some(s => normalizePackageSize(s) === normalizePackageSize(product.quantity));
    const score = (brand ? 25 : 0) + Math.round(name * 50) + (size ? 20 : 0);
    const matchedFields = [brand && "brand", name >= .5 && "product name", size && "package size"].filter(Boolean);
    return { score, matchMethod: "product_similarity", matchedFields, exactBarcode: false, equivalentBarcode: false, usedSimilarity: true, reason: matchedFields.length ? `Similar product details: ${matchedFields.join(", ")}.` : "Related wording in the recall record." };
  }
  function classifyResult(product, recalls) {
    const ranked = recalls.map(recall => ({ recall, ...scoreRecall(product, recall) })).sort((a, b) => b.score - a.score); const best = ranked[0];
    if (!best || best.score < 35) return { status: "no_matching_recall" };
    if (best.score < 75) return { status: "possible_match_manual_review", ...best };
    if ((best.recall.lotCodes || []).length || (best.recall.dateCodes || []).length) return { status: "possible_match_details_required", unresolvedDetails: [...(best.recall.lotCodes || []).map(() => "lot code"), ...(best.recall.dateCodes || []).map(() => "date code")], ...best };
    return best.usedSimilarity ? { status: "possible_match_manual_review", ...best } : { status: "confirmed_match", ...best };
  }
  function lotCodeMatches(input, recall) { const value = normalizeText(input).replace(/\s/g, ""); return [...(recall.lotCodes || []), ...(recall.dateCodes || [])].some(code => normalizeText(code).replace(/\s/g, "") === value); }
  function validateRecallData(data) { return Boolean(data && typeof data.generatedAt === "string" && Array.isArray(data.sources) && Array.isArray(data.recalls)); }
  function dataAgeDays(generatedAt, now = Date.now()) { const time = Date.parse(generatedAt); return Number.isFinite(time) ? Math.max(0, Math.floor((now - time) / 86400000)) : Infinity; }
  function isRecallDataUsable(data) { return validateRecallData(data) && Boolean(data.dataHealth) && Object.values(data.dataHealth.sources || {}).some(source => source.success || source.recordCount > 0); }

  async function loadJson(url) { const response = await fetch(url); if (!response.ok) throw new Error(`Request failed (${response.status})`); return response.json(); }
  async function loadData() {
    const results = await Promise.allSettled([loadJson(CONFIG.recallUrl), loadJson(CONFIG.demoUrl), loadJson(CONFIG.demoRecallUrl)]);
    if (results[0].status === "fulfilled" && validateRecallData(results[0].value)) { state.recalls = results[0].value; const date = new Date(state.recalls.generatedAt).toLocaleString(); const usable = isRecallDataUsable(state.recalls); $("data-notice").className = usable ? "notice" : "notice error"; $("data-notice").textContent = usable ? `Live Check · Official recall data updated ${date}` : "Live Check is unavailable until at least one official source has valid recall data. Demo Mode remains available."; $("footer-updated").textContent = `Official data timestamp: ${date}.`; renderDataStatus(state.recalls); } else { $("data-notice").className = "notice error"; $("data-notice").textContent = "Official recall data could not be loaded. Demo Mode remains available; Live Check will not show a no-match conclusion."; renderDataStatus(null); }
    if (results[1].status === "fulfilled" && Array.isArray(results[1].value.products)) state.demos = results[1].value.products;
    if (results[2].status === "fulfilled" && validateRecallData(results[2].value)) state.demoRecalls = results[2].value;
    renderDemos();
  }
  function renderDataStatus(data) { const root = $("data-status-content"); root.replaceChildren(); if (!data?.dataHealth) { root.append(el("p", "Data-health metadata is unavailable.")); return; } const health = data.dataHealth; const age = dataAgeDays(data.generatedAt); root.append(el("p", `Last successful update: ${health.lastSuccessfulUpdate ? new Date(health.lastSuccessfulUpdate).toLocaleString() : "none recorded"}. Data age: ${Number.isFinite(age) ? `${age} day${age === 1 ? "" : "s"}` : "unknown"}.`)); ["FDA", "USDA"].forEach(agency => { const source = health.sources?.[agency] || {}; root.append(el("p", `${agency}: ${source.success ? "available" : "unavailable or retained"} · ${source.recordCount || 0} records${source.error ? ` · ${source.error}` : ""}`)); }); if (age > CONFIG.staleDays) root.append(el("p", `Warning: official data is stale (more than ${CONFIG.staleDays} days old).`, "field-error")); const available = ["FDA", "USDA"].filter(a => health.sources?.[a]?.success || health.sources?.[a]?.recordCount > 0); if (available.length === 1) root.append(el("p", `Only ${available[0]} data is available. Results do not cover both agencies.`, "field-error")); (health.warnings || []).forEach(warning => root.append(el("p", warning, "field-error"))); }
  function renderDemos() { const list = $("demo-list"); list.replaceChildren(); list.setAttribute("aria-busy", "false"); if (!state.demos.length) { list.append(el("p", "Demo products could not be loaded.")); return; } state.demos.forEach(demo => { const button = el("button", null, "demo-card"); button.type = "button"; button.append(el("strong", demo.label), el("span", demo.description)); button.addEventListener("click", () => checkProduct(demo.code, { demo })); list.append(button); }); }

  async function identifyProductWithOpenFoodFacts(code, options = {}) {
    if (options.demo) return options.demo.product || null;
    const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), options.timeout ?? CONFIG.timeout); const fetcher = options.fetchImpl || fetch;
    try { const fields = "code,product_name,generic_name,brands,quantity,image_front_small_url,categories,countries,manufacturing_places,owner_fields"; const response = await fetcher(`${CONFIG.offUrl}${encodeURIComponent(code)}.json?fields=${fields}`, { signal: controller.signal, headers: { "Accept": "application/json", "X-Requested-With": "RecallCheck" } }); if (response.status === 429) throw new Error("rate_limit"); if (!response.ok) throw new Error("service"); const body = await response.json(); if (!body || typeof body.status !== "number") throw new Error("malformed"); return body.status === 1 && body.product ? body.product : null; } catch (error) { if (error.name === "AbortError") throw new Error("timeout"); throw error; } finally { clearTimeout(timer); }
  }
  async function checkProduct(rawCode, options = {}) {
    const code = normalizeBarcode(rawCode); if (!isRecognizedLength(code)) { renderStandaloneStatus("invalid_barcode", "Enter an 8, 12, 13, or 14-digit barcode."); return; }
    stopScanner(); showResultsLoading(code);
    let product;
    try { product = await identifyProductWithOpenFoodFacts(code, options); } catch (error) { product = { code, product_name: "Product details unavailable", brands: "Unknown", quantity: "Unknown", _serviceMessage: error.message === "timeout" ? "The product service timed out. Local recall records were still checked by barcode." : "The product-information service is temporarily unavailable. Local recall records were still checked by barcode." }; }
    if (!product) { renderProduct({ code, product_name: "Product not identified", brands: "Unknown", quantity: "Unknown" }); const dataset = options.demo ? state.demoRecalls : state.recalls; if (!dataset || (!options.demo && !isRecallDataUsable(dataset))) return renderStatus({ status: "recall_data_unavailable", isDemo: Boolean(options.demo) }); const byCode = dataset.recalls.filter(r => exactCodeMatch(code, r)); if (byCode.length) return renderStatus({ ...classifyResult({ code, product_name: "", brands: "", quantity: "" }, byCode), isDemo: Boolean(options.demo) }); return renderStatus({ status: "product_not_found", isDemo: Boolean(options.demo), matchMethod: "direct_identifier_search", matchedFields: [], exactBarcode: false, equivalentBarcode: false, usedSimilarity: false }); }
    product.code = code; renderProduct(product);
    const dataset = options.demo ? state.demoRecalls : state.recalls;
    if (!dataset || (!options.demo && !isRecallDataUsable(dataset))) return renderStatus({ status: "recall_data_unavailable" });
    const outcome = options.demo?.forcedStatus ? { status: options.demo.forcedStatus, recall: dataset.recalls.find(r => r.id === options.demo.recallId), reason: options.demo.reason, matchMethod: "demo_scenario", matchedFields: ["fictional demo setup"], exactBarcode: options.demo.forcedStatus !== "possible_match_manual_review", equivalentBarcode: false, usedSimilarity: options.demo.forcedStatus === "possible_match_manual_review" } : classifyResult(product, dataset.recalls);
    outcome.isDemo = Boolean(options.demo);
    renderStatus(outcome);
  }
  function showResultsLoading(code) { $("results").hidden = false; $("product-summary").replaceChildren(); $("result-panel").replaceChildren(el("div", `Checking barcode ${code}…`, "status")); $("results").focus(); }
  function renderProduct(product) { const wrap = el("article", null, "product"); let image; if (product.image_front_small_url) { image = el("img"); image.src = product.image_front_small_url; image.alt = `${product.product_name || "Product"} package`; image.referrerPolicy = "no-referrer"; } else { image = el("div", "▧", "image-placeholder"); image.setAttribute("role", "img"); image.setAttribute("aria-label", "No product image available"); } const info = el("div"); info.append(el("p", "Product information · Open Food Facts", "eyebrow"), el("h2", product.product_name || product.generic_name || "Unnamed product"), el("p", `${product.brands || "Brand unavailable"} · ${product.quantity || "Size unavailable"}`), el("p", `Barcode ${product.code}`), el("small", "Open Food Facts is community maintained and is not an authoritative recall source.")); wrap.append(image, info); const content = [wrap]; if (product._serviceMessage) { const warning = el("aside", null, "status warning"); warning.append(el("h2", "Product service unavailable"), el("p", product._serviceMessage)); content.push(warning); } $("product-summary").replaceChildren(...content); $("results").hidden = false; }
  const outcomeCopy = { confirmed_match: ["Recall match found", "Do not consume or use this product. Follow the instructions in the official recall notice.", "danger"], possible_match_details_required: ["This product may be affected", "A recall was found for this product, but only certain lots, packages, or dates may be included.", "warning"], possible_match_manual_review: ["A related recall needs manual review", "Product details overlap with a recall record, but the barcode was not an exact match. Compare the official notice carefully.", "warning"], no_matching_recall: ["No matching recall was found", "", "ok"], product_not_found: ["Product could not be identified", "The barcode was read, but Open Food Facts did not identify the product. Its barcode was still checked against the local recall records; no exact barcode record was found.", "warning"], recall_data_unavailable: ["Recall data is unavailable", "Recall records could not be loaded, so this tool cannot provide a recall result. Check the official FDA and USDA sources.", "danger"], product_service_unavailable: ["Product service unavailable", "Open Food Facts could not be reached. This is separate from the local recall-data service.", "warning"], invalid_barcode: ["Barcode needs attention", "Enter a recognized barcode length.", "warning"] };
  function renderStatus(outcome) { const [title, defaultBody, tone] = outcomeCopy[outcome.status] || outcomeCopy.possible_match_manual_review; const box = el("article", null, `status ${tone}`); box.append(el("p", `${outcome.isDemo ? "DEMO MODE · FICTIONAL DATA · " : "LIVE CHECK · OFFICIAL DATA · "}${outcome.status.replaceAll("_", " ")}`.toUpperCase(), "eyebrow"), el("h2", title)); let body = defaultBody; const dataset = outcome.isDemo ? state.demoRecalls : state.recalls; if (outcome.status === "no_matching_recall") { const available = outcome.isDemo ? [] : ["FDA", "USDA"].filter(a => dataset.dataHealth?.sources?.[a]?.success || dataset.dataHealth?.sources?.[a]?.recordCount > 0); const coverage = outcome.isDemo ? "fictional demo" : available.join(" and ") || "official"; body = `No matching recall was found in the ${coverage} data checked as of ${new Date(dataset.generatedAt).toLocaleString()}. This does not guarantee that the product is safe or that a new recall has not been issued.${!outcome.isDemo && available.length === 1 ? ` ${available[0]} was the only available official source.` : ""}`; } box.append(el("p", body)); if (outcome.recall) appendRecallDetails(box, outcome.recall, outcome.status, dataset); if (outcome.matchMethod || outcome.reason) appendTransparency(box, outcome); $("result-panel").replaceChildren(box); $("results").hidden = false; $("results").focus(); }
  function appendTransparency(box, outcome) { const details = el("details", null, "transparency"); details.append(el("summary", "Why am I seeing this?")); const list = el("dl", null, "details"); [["Match method", outcome.matchMethod || "No identifier or similarity match"], ["Matched fields", (outcome.matchedFields || []).join(", ") || "None"], ["Barcode", outcome.exactBarcode ? "Exact" : outcome.equivalentBarcode ? "Equivalent GTIN representation" : "Not matched"], ["Similarity used", outcome.usedSimilarity ? "Yes—never sufficient for confirmation" : "No"], ["Unresolved package details", (outcome.unresolvedDetails || []).join(", ") || "None"], ["Official source record ID", outcome.recall?.sourceRecordId || outcome.recall?.id || "None"]].forEach(([term, value]) => list.append(el("dt", term), el("dd", value))); details.append(list); if (outcome.reason) details.append(el("p", outcome.reason)); box.append(details); }
  function renderStandaloneStatus(status, message, product) { $("results").hidden = false; if (product) renderProduct({ code: product.code, product_name: "Product details unavailable", brands: "Unknown", quantity: "Unknown" }); const box = el("article", null, `status ${outcomeCopy[status][2]}`); box.append(el("h2", outcomeCopy[status][0]), el("p", message)); $("result-panel").replaceChildren(box); $("results").focus(); }
  function appendRecallDetails(box, recall, status, dataset) { const dl = el("dl", null, "details"); [["Agency", recall.agency], ["Type", recall.type], ["Recall date", recall.recallDate || "Not listed"], ["Classification", recall.classification], ["Company", recall.recallingFirm], ["Reason", recall.reason], ["Affected codes", [...(recall.lotCodes || []), ...(recall.dateCodes || [])].join(", ") || "No lot/date restriction listed"], ["Distribution", recall.distribution]].forEach(([term, value]) => { dl.append(el("dt", term), el("dd", value || "Not listed")); }); box.append(dl); const link = el("a", `View official ${recall.agency} source ↗`, "primary"); link.href = recall.officialUrl; link.target = "_blank"; link.rel = "noopener noreferrer"; box.append(link, el("p", `${dataset.datasetLabel || "Official recall dataset"} timestamp: ${new Date(dataset.generatedAt).toLocaleString()}.`)); if (status === "possible_match_details_required") appendLotForm(box, recall); }
  function appendLotForm(box, recall) { const form = el("form", null, "lot-form"); const heading = el("h3", "Check your lot or date code"); const label = el("label", "Lot, best-by, use-by, or date code"); const input = el("input"); input.name = "package-code"; input.autocomplete = "off"; label.htmlFor = input.id = "package-code"; const help = el("p", "Look near the seal, nutrition panel, package bottom, or cap. Enter the code exactly as printed."); const submit = el("button", "Check package code", "primary"); submit.type = "submit"; const cannot = el("button", "I cannot find it", "text-button"); cannot.type = "button"; const result = el("p"); result.setAttribute("role", "status"); form.append(heading, help, label, input, submit, cannot, result); form.addEventListener("submit", e => { e.preventDefault(); if (lotCodeMatches(input.value, recall)) renderStatus({ status: "confirmed_match", recall, reason: "The entered package code matches the recall record." }); else { result.textContent = "That code did not exactly match the listed codes. This is not a safety guarantee—review the official notice."; result.className = "field-error"; } }); cannot.addEventListener("click", () => { result.textContent = "If you cannot find the code, do not assume the package is unaffected. Use the official notice or contact the manufacturer."; }); box.append(form); }

  function openManual() { stopScanner(); $("scanner-dialog").open && $("scanner-dialog").close(); $("manual-section").hidden = false; $("barcode-input").focus(); }
  function submitBarcode(force = false) { const code = normalizeBarcode($("barcode-input").value); $("continue-invalid").hidden = true; if (!isRecognizedLength(code)) { $("barcode-error").textContent = "Enter 8, 12, 13, or 14 digits."; return; } if (!validateCheckDigit(code) && !force) { state.pendingBarcode = code; $("barcode-error").textContent = "The check digit appears invalid. Correct the barcode or continue with a warning."; $("continue-invalid").hidden = false; return; } $("barcode-error").textContent = ""; checkProduct(code); }
  async function startScanner() { state.lastFocus = document.activeElement; const dialog = $("scanner-dialog"); dialog.showModal(); $("scanner-close").focus(); if (!window.isSecureContext) return scannerError("Camera access requires HTTPS or localhost. Enter the barcode instead."); if (!navigator.mediaDevices?.getUserMedia) return scannerError("This browser does not provide camera access. Enter the barcode instead."); if (!window.ZXingBrowser?.BrowserMultiFormatReader) return scannerError("The scanner library did not load. Check your connection or enter the barcode instead."); $("scanner-status").textContent = "Requesting camera permission…"; try { const reader = new window.ZXingBrowser.BrowserMultiFormatReader(); state.scannerControls = await reader.decodeFromConstraints({ audio: false, video: { facingMode: { ideal: "environment" } } }, $("scanner-video"), (result, error, controls) => { if (result) { const code = normalizeBarcode(result.getText()); if (code && code !== state.lastScan) { state.lastScan = code; controls.stop(); stopScanner(); dialog.close(); checkProduct(code); } } }); state.stream = $("scanner-video").srcObject; $("scanner-status").textContent = "Camera active. Hold the barcode inside the frame."; } catch (error) { const name = error?.name; scannerError(name === "NotAllowedError" ? "Camera permission was denied. Allow access in browser settings or enter the barcode instead." : name === "NotFoundError" ? "No camera was found. Enter the barcode instead." : "The camera could not start. Close other camera apps or enter the barcode instead."); } }
  function scannerError(message) { stopScanner(); $("scanner-status").textContent = message; }
  function stopScanner() { if (state.scannerControls) { state.scannerControls.stop(); state.scannerControls = null; } const stream = state.stream || $("scanner-video")?.srcObject; stream?.getTracks().forEach(track => track.stop()); state.stream = null; if ($("scanner-video")) $("scanner-video").srcObject = null; }
  function closeScanner() { stopScanner(); if ($("scanner-dialog").open) $("scanner-dialog").close(); state.lastFocus?.focus(); }
  function bindEvents() { $("scan-button").addEventListener("click", startScanner); $("manual-button").addEventListener("click", openManual); $("scanner-close").addEventListener("click", closeScanner); $("scanner-stop").addEventListener("click", closeScanner); $("scanner-manual").addEventListener("click", () => { closeScanner(); openManual(); }); $("scanner-dialog").addEventListener("cancel", e => { e.preventDefault(); closeScanner(); }); $("barcode-form").addEventListener("submit", e => { e.preventDefault(); submitBarcode(); }); $("continue-invalid").addEventListener("click", () => submitBarcode(true)); window.addEventListener("pagehide", stopScanner); document.addEventListener("visibilitychange", () => { if (document.hidden) stopScanner(); }); }
  window.RecallCheck = Object.freeze({ normalizeBarcode, generateGtinVariants, validateCheckDigit, normalizeText, normalizeBrand, normalizePackageSize, exactCodeMatch, productNameTokenComparison, scoreRecall, classifyResult, lotCodeMatches, validateRecallData, dataAgeDays, isRecallDataUsable, identifyProductWithOpenFoodFacts });
  bindEvents(); loadData(); if ("serviceWorker" in navigator) navigator.serviceWorker.register("./sw.js").catch(() => {});
})();
