(() => {
  "use strict";
  const CONFIG = { recallUrl: "data/recalls.json", demoRecallUrl: "data/demo-recalls.json", demoUrl: "data/demo-products.json", offUrl: "https://world.openfoodfacts.org/api/v2/product/", timeout: 9000, staleDays: 8 };
  const state = { recalls: null, demoRecalls: null, demos: [], scannerControls: null, stream: null, lastScan: "", pendingBarcode: "", lastFocus: null };
  const $ = (id) => document.getElementById(id);
  const el = (tag, text, className) => { const node = document.createElement(tag); if (text != null) node.textContent = text; if (className) node.className = className; return node; };

  function normalizeBarcode(value) { return String(value ?? "").replace(/[\s-]/g, "").replace(/[^0-9]/g, ""); }
  function isRecognizedLength(code) { return [8, 12, 13, 14].includes(normalizeBarcode(code).length); }
  function validateCheckDigit(value) {
    const code = normalizeBarcode(value); if (!isRecognizedLength(code)) return false;
    const digits = [...code].map(Number); const supplied = digits.pop();
    const sum = digits.reverse().reduce((total, digit, i) => total + digit * (i % 2 === 0 ? 3 : 1), 0);
    return (10 - (sum % 10)) % 10 === supplied;
  }
  function generateGtinVariants(value) {
    const code = normalizeBarcode(value); const variants = new Set([code]);
    if (code.length === 12) { variants.add(`0${code}`); variants.add(`00${code}`); }
    if (code.length === 13) { variants.add(`0${code}`); if (code.startsWith("0")) variants.add(code.slice(1)); }
    if (code.length === 14) { if (code.startsWith("0")) variants.add(code.slice(1)); if (code.startsWith("00")) variants.add(code.slice(2)); }
    return [...variants].filter(Boolean);
  }
  function normalizeText(value) { return String(value ?? "").normalize("NFKD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim(); }
  function normalizeBrand(value) { return normalizeText(value).replace(/\b(inc|llc|company|co)\b/g, "").replace(/\s+/g, " ").trim(); }
  function normalizePackageSize(value) { return normalizeText(value).replace(/\bounces?\b/g, "oz").replace(/\bpounds?\b/g, "lb").replace(/\s+/g, ""); }
  function exactCodeMatch(code, recall) { const variants = new Set(generateGtinVariants(code)); return [...(recall.upcs || []), ...(recall.gtins || [])].some(item => generateGtinVariants(item).some(v => variants.has(v))); }
  function productNameTokenComparison(a, b) { const ignored = new Set(["the", "and", "with", "food"]); const x = new Set(normalizeText(a).split(" ").filter(t => t.length > 2 && !ignored.has(t))); const y = new Set(normalizeText(b).split(" ").filter(t => t.length > 2 && !ignored.has(t))); if (!x.size || !y.size) return 0; return [...x].filter(t => y.has(t)).length / Math.min(x.size, y.size); }
  function scoreRecall(product, recall) {
    const raw = normalizeBarcode(product.code); const recallCodes = [...(recall.upcs || []), ...(recall.gtins || [])];
    const exact = recallCodes.some(code => normalizeBarcode(code) === raw);
    if (exactCodeMatch(product.code, recall)) return { score: 100, matchMethod: exact ? "exact_identifier" : "equivalent_gtin", matchedFields: [exact ? "barcode" : "equivalent GTIN"], exactBarcode: exact, equivalentBarcode: !exact, usedSimilarity: false, reason: `The ${exact ? "exact barcode" : "equivalent GTIN representation"} matches an identifier in the official record.` };
    const brand = (recall.brandNames || []).some(b => normalizeBrand(b) === normalizeBrand(product.brands));
    const name = Math.max(0, ...(recall.productNames || []).map(n => productNameTokenComparison(product.product_name, n)));
    const size = (recall.packageSizes || []).some(s => normalizePackageSize(s) === normalizePackageSize(product.quantity));
    const score = (brand ? 25 : 0) + Math.round(name * 50) + (size ? 20 : 0);
    const matchedFields = [brand && "brand", name >= .5 && "product name", size && "package size"].filter(Boolean);
    return { score, matchMethod: "product_similarity", matchedFields, exactBarcode: false, equivalentBarcode: false, usedSimilarity: true, reason: matchedFields.length ? `Similar product details: ${matchedFields.join(", ")}.` : "Related wording in the recall record." };
  }
  function classifyResult(product, recalls) {
    const ranked = recalls.map(recall => ({ recall, ...scoreRecall(product, recall) })).sort((a, b) => b.score - a.score); const best = ranked[0];
    if (!best || best.score < 35) return { status: "no_matching_recall" };
    if (best.score < 75) return { status: "possible_match_manual_review", ...best };
    if ((best.recall.lotCodes || []).length || (best.recall.dateCodes || []).length) return { status: "possible_match_details_required", unresolvedDetails: [...(best.recall.lotCodes || []).map(() => "lot code"), ...(best.recall.dateCodes || []).map(() => "date code")], ...best };
    return best.usedSimilarity ? { status: "possible_match_manual_review", ...best } : { status: "confirmed_match", ...best };
  }
  function lotCodeMatches(input, recall) { const value = normalizeText(input).replace(/\s/g, ""); return [...(recall.lotCodes || []), ...(recall.dateCodes || [])].some(code => normalizeText(code).replace(/\s/g, "") === value); }
  function validateRecallData(data) { return Boolean(data && typeof data.generatedAt === "string" && Array.isArray(data.sources) && Array.isArray(data.recalls)); }
  function dataAgeDays(generatedAt, now = Date.now()) { const time = Date.parse(generatedAt); return Number.isFinite(time) ? Math.max(0, Math.floor((now - time) / 86400000)) : Infinity; }
  function isRecallDataUsable(data) { return validateRecallData(data) && Boolean(data.dataHealth) && Object.values(data.dataHealth.sources || {}).some(source => source.success || source.recordCount > 0); }

  async function loadJson(url) { const response = await fetch(url); if (!response.ok) throw new Error(`Request failed (${response.status})`); return response.json(); }
  async function loadData() {
    const results = await Promise.allSettled([loadJson(CONFIG.recallUrl), loadJson(CONFIG.demoUrl), loadJson(CONFIG.demoRecallUrl)]);
    if (results[0].status === "fulfilled" && validateRecallData(results[0].value)) { state.recalls = results[0].value; const when = new Date(state.recalls.generatedAt); const date = when.toLocaleString(); const today = new Date().toDateString() === when.toDateString(); const usable = isRecallDataUsable(state.recalls); $("data-notice").textContent = usable ? (today ? "Recall data updated today" : `Recall data last updated ${when.toLocaleDateString()}`) : "Official recall coverage is currently unavailable"; $("footer-updated").textContent = `Recall data last updated ${date}.`; renderDataStatus(state.recalls); } else { $("data-notice").textContent = "Official recall coverage could not be loaded"; renderDataStatus(null); }
    if (results[1].status === "fulfilled" && Array.isArray(results[1].value.products)) state.demos = results[1].value.products;
    if (results[2].status === "fulfilled" && validateRecallData(results[2].value)) state.demoRecalls = results[2].value;
    renderDemos();
  }
  function formatSourceError(error) { if (!error) return ""; if (typeof error === "string") return error; const prefix = error.httpStatus != null ? `HTTP ${error.httpStatus}` : (error.type || "Request error"); return `${prefix}${error.message || error.httpReason ? ` — ${error.message || error.httpReason}` : ""}`; }
  function renderDataStatus(data) { const root = $("data-status-content"); root.replaceChildren(); if (!data?.dataHealth) { root.append(el("p", "Recall data coverage details are unavailable.")); return; } const health=data.dataHealth, age=dataAgeDays(data.generatedAt); ["FDA","USDA"].forEach(agency=>{const source=health.sources?.[agency]||{};root.append(el("p",`${agency === "FDA" ? "FDA food" : "USDA meat and poultry"} recall data is ${source.success || source.recordCount > 0 ? "available" : "unavailable"}.`));}); root.append(el("p",`Recall data was last updated ${new Date(data.generatedAt).toLocaleString()}.`)); const technical=el("details",null,"technical"),summary=el("summary","Technical details"),body=el("div"); body.append(el("p",`Data age: ${Number.isFinite(age)?`${age} day${age===1?"":"s"}`:"unknown"}. Last successful update: ${health.lastSuccessfulUpdate?new Date(health.lastSuccessfulUpdate).toLocaleString():"not recorded"}.`)); ["FDA","USDA"].forEach(agency=>{const source=health.sources?.[agency]||{},error=formatSourceError(source.error);body.append(el("p",`${agency}: ${source.recordCount||0} records${error?` · ${error}`:""}`));}); (health.warnings||[]).forEach(w=>body.append(el("p",w,"field-error"))); technical.append(summary,body); root.append(technical); }
  function renderDemos() { const list = $("demo-list"); list.replaceChildren(); list.setAttribute("aria-busy", "false"); if (!state.demos.length) { list.append(el("p", "Demo products could not be loaded.")); return; } state.demos.forEach(demo => { const button = el("button", null, "demo-card"); button.type = "button"; button.append(el("strong", demo.label), el("span", demo.description)); button.addEventListener("click", () => checkProduct(demo.code, { demo })); list.append(button); }); }

  async function identifyProductWithOpenFoodFacts(code, options = {}) {
    if (options.demo) return options.demo.product || null;
    const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), options.timeout ?? CONFIG.timeout); const fetcher = options.fetchImpl || fetch;
    try { const fields = "code,product_name,generic_name,brands,quantity,image_front_small_url,categories,countries,manufacturing_places,owner_fields"; const response = await fetcher(`${CONFIG.offUrl}${encodeURIComponent(code)}.json?fields=${fields}`, { signal: controller.signal, headers: { "Accept": "application/json", "X-Requested-With": "RecallCheck" } }); if (response.status === 429) throw new Error("rate_limit"); if (!response.ok) throw new Error("service"); const body = await response.json(); if (!body || typeof body.status !== "number") throw new Error("malformed"); return body.status === 1 && body.product ? body.product : null; } catch (error) { if (error.name === "AbortError") throw new Error("timeout"); throw error; } finally { clearTimeout(timer); }
  }
  function setProgress(step, productFound = true) {
    $("lookup-progress").hidden = false;
    const items = [$("progress-barcode"), $("progress-product"), $("progress-recalls")];
    items.forEach((item, i) => { item.className = i < step ? "done" : i === step ? "active" : ""; });
    if (step === 0) $("progress-announcement").textContent = "Barcode captured. Identifying product.";
    if (step === 1) $("progress-announcement").textContent = `${productFound ? "Product identified" : "Product information not found"}. Checking FDA and USDA recalls.`;
  }
  function sourceAvailability(dataset) { return ["FDA", "USDA"].filter(a => dataset?.dataHealth?.sources?.[a]?.success || dataset?.dataHealth?.sources?.[a]?.recordCount > 0); }
  function makeProductCard(product) { const wrap = el("article", null, "product"); let image; if (product.image_front_small_url) { image = el("img"); image.src = product.image_front_small_url; image.alt = `${product.product_name || "Product"} package`; image.referrerPolicy = "no-referrer"; } else { image = el("div", "▧", "image-placeholder"); image.setAttribute("role", "img"); image.setAttribute("aria-label", "Product image unavailable"); } const info = el("div"); info.append(el("h3", product.product_name || product.generic_name || "Name unavailable"), el("p", `Brand: ${product.brands || "Unavailable"}`), el("p", `Package size: ${product.quantity || "Unavailable"}`), el("p", `Barcode: ${product.code}`)); wrap.append(image, info); return wrap; }
  async function checkProduct(rawCode, options = {}) {
    const code = normalizeBarcode(rawCode); if (!isRecognizedLength(code)) return renderStandaloneStatus("invalid_barcode", "Enter an 8, 12, 13, or 14-digit barcode.");
    stopScanner(); resetCheck(false); setProgress(0); state.pendingBarcode = code;
    let product = null, productError = "";
    try { product = await identifyProductWithOpenFoodFacts(code, options); } catch (error) { productError = error.message; }
    setProgress(1, Boolean(product)); await new Promise(resolve => setTimeout(resolve, options.demo ? 50 : 180));
    const dataset = options.demo ? state.demoRecalls : state.recalls;
    if (!dataset || (!options.demo && !isRecallDataUsable(dataset))) { $("lookup-progress").hidden = true; renderStatus({ status:"recall_data_unavailable", productServiceUnavailable:Boolean(productError), isDemo:Boolean(options.demo) }); return; }
    const direct = dataset.recalls.filter(r => exactCodeMatch(code, r));
    if (!product) { $("lookup-progress").hidden = true; if (direct.length) return renderStatus({ ...classifyResult({code,product_name:"",brands:"",quantity:""}, direct), isDemo:Boolean(options.demo), productServiceUnavailable:Boolean(productError) }); return renderStatus({ status:"product_not_found", isDemo:Boolean(options.demo), productServiceUnavailable:Boolean(productError), matchMethod:"direct_identifier_search", matchedFields:[] }); }
    product.code = code; state.pendingProduct = product; state.pendingOptions = options;
    const outcome = options.demo?.forcedStatus ? { status:options.demo.forcedStatus, recall:dataset.recalls.find(r=>r.id===options.demo.recallId), reason:options.demo.reason, matchMethod:"demo_scenario", matchedFields:["fictional demo setup"], exactBarcode:options.demo.forcedStatus!=="possible_match_manual_review", usedSimilarity:options.demo.forcedStatus==="possible_match_manual_review" } : classifyResult(product,dataset.recalls);
    outcome.isDemo=Boolean(options.demo); state.pendingOutcome=outcome; $("lookup-progress").hidden=true;
    if (outcome.status === "confirmed_match" || outcome.status === "possible_match_details_required") { renderProduct(product); renderStatus(outcome); return; }
    $("confirmation-product").replaceChildren(makeProductCard(product)); $("product-confirmation").hidden=false; $("confirmation-title").focus?.();
  }
  function continueConfirmedProduct() { $("product-confirmation").hidden=true; renderProduct(state.pendingProduct); renderStatus(state.pendingOutcome); }
  function renderProduct(product) { const correction=el("button","Not my product","text-button"); correction.type="button"; correction.addEventListener("click",()=>{ $("results").hidden=true; $("confirmation-product").replaceChildren(makeProductCard(product)); $("product-confirmation").hidden=false; $("correction-actions").hidden=false; }); $("product-summary").replaceChildren(makeProductCard(product), el("p", "Product information supplied by Open Food Facts and may be incomplete.", "coverage-line"), correction); }
  const outcomeCopy = {
    confirmed_match:["!","Recall found","Do not eat or serve this product until you review the official recall instructions.","danger"],
    possible_match_details_required:["?","Check the package","This product may be affected, but the recall applies only to certain lots, dates, package sizes, or establishment codes.","warning"],
    possible_match_manual_review:["≈","Review this possible match","RecallCheck found a similar product, but the barcode did not produce an exact official match.","warning"],
    no_matching_recall:["i","No matching recall found","RecallCheck did not find this barcode in the FDA or USDA records currently available.","neutral"],
    product_not_found:["?","Product information not found","We could not identify this barcode through the product-information service. We continued checking the barcode directly against official recall records.","warning"],
    recall_data_unavailable:["!","We could not complete the check","Official recall records were unavailable, so RecallCheck cannot provide a result.","danger"],
    invalid_barcode:["!","Barcode needs attention","Enter a recognized barcode length.","warning"]
  };
  function addOfficialLinks(box) { const p=el("p"); const f=el("a","Search FDA recalls"); f.href="https://www.fda.gov/safety/recalls-market-withdrawals-safety-alerts"; const u=el("a","Search USDA recalls"); u.href="https://www.fsis.usda.gov/recalls"; [f,u].forEach(a=>{a.target="_blank";a.rel="noopener noreferrer";}); p.append(f," · ",u); box.append(p); }
  function renderStatus(outcome) { const [icon,title,copy,tone]=outcomeCopy[outcome.status]||outcomeCopy.possible_match_manual_review; const box=el("article",null,`status ${tone}`); box.append(el("span",icon,"result-icon")); const heading=el("h2",title,"result-heading"); heading.id="completed-result-heading"; heading.tabIndex=-1; box.append(heading,el("p",copy)); const dataset=outcome.isDemo?state.demoRecalls:state.recalls; const available=sourceAvailability(dataset);
    if(outcome.status==="confirmed_match") box.append(el("p","This product matches an official FDA or USDA recall record."));
    if(outcome.status==="possible_match_manual_review") box.append(el("p","Compare your package with the official recall notice before using the product.","instruction"));
    if(outcome.status==="no_matching_recall") { box.append(el("p","This does not guarantee that the product is safe. Some recall notices do not include barcodes, and recall information can change.","instruction"),el("p",`Agencies checked: ${available.join(" and ") || "none"}. Recall data last updated ${new Date(dataset.generatedAt).toLocaleString()}.`)); addOfficialLinks(box); }
    if(outcome.status==="recall_data_unavailable") { const missing=["FDA","USDA"].filter(a=>!available.includes(a)); box.append(el("p",`${missing.length===2?"FDA and USDA data are":`${missing.join(" and ")} data is`} unavailable.${available.length?` Partial coverage is available from ${available.join(" and ")}, but no no-match conclusion will be shown.`:" Neither official source could be checked."}`)); if(outcome.productServiceUnavailable) box.append(el("p","The product-information service was also unavailable.")); addOfficialLinks(box); }
    if(outcome.status==="product_not_found") { if(outcome.productServiceUnavailable) box.append(el("p","The product service was unavailable; this is separate from recall-data availability.")); addOfficialLinks(box); }
    if(outcome.recall) appendRecallDetails(box,outcome.recall,outcome.status,dataset);
    appendTransparency(box,outcome); appendRepeatActions(box); $("result-panel").replaceChildren(box); $("results").hidden=false; heading.focus(); }
  function appendTransparency(box,outcome){const d=el("details",null,"transparency");d.append(el("summary","Why am I seeing this?"));const p=el("p", outcome.reason || (outcome.status==="no_matching_recall"?"No exact identifier or sufficiently similar official record was found.":outcome.status==="product_not_found"?"Open Food Facts did not return a product, and direct official barcode matching found no record.":"Recall-data availability determines whether a result can be completed."));d.append(p);if(outcome.matchMethod){const dl=el("dl",null,"details");[["Match method",outcome.matchMethod],["What matched",(outcome.matchedFields||[]).join(", ")||"No fields"],["Barcode similarity",outcome.exactBarcode?"Exact":outcome.equivalentBarcode?"Equivalent GTIN":"Not exact"],["Lot or date information",(outcome.unresolvedDetails||[]).join(", ")||"None unresolved"]].forEach(([a,b])=>dl.append(el("dt",a),el("dd",b)));d.append(dl);}box.append(d);}
  function appendRecallDetails(box,recall,status,dataset){const dl=el("dl",null,"details");[["Agency",recall.agency],["Recall classification",recall.classification],["Recalling company",recall.recallingFirm],["Affected product",(recall.productNames||[]).join(", ")||recall.productDescription],["Recall reason",recall.reason],["Recall date",recall.recallDate],["Affected lot, date, or package",[...(recall.lotCodes||[]),...(recall.dateCodes||[]),...(recall.packageSizes||[])].join(", ")||"Not listed"]].forEach(([a,b])=>dl.append(el("dt",a),el("dd",b||"Not listed")));box.append(dl);const link=el("a","View official recall","primary");link.href=recall.officialUrl;link.target="_blank";link.rel="noopener noreferrer";box.append(link);if(status==="confirmed_match"){const h=el("h3","What to do next"),ol=el("ol",null,"next-steps");["Check the lot, date, establishment, or package code.","Follow the official recall notice.","Return or discard the product as directed.","Seek medical advice if someone may be ill."].forEach(x=>ol.append(el("li",x)));box.append(h,ol);}if(status==="possible_match_details_required")appendLotForm(box,recall);}
  function codeHelp(){const aside=el("aside",null,"code-help");aside.append(el("h3","Where to find a package code"),el("p","Look for printed letters and numbers. Common labels include “Best By,” “Use By,” “LOT,” or an establishment number such as “EST.”"));const ul=el("ul",null,"code-locations");["Top seal","Bottom panel","Side seam","Cap","Near the barcode or nutrition label","Establishment code area"].forEach(x=>ul.append(el("li",x)));aside.append(ul);return aside;}
  function appendLotForm(box,recall){box.append(codeHelp());const form=el("form",null,"lot-form"),label=el("label","Package code"),input=el("input");input.id="package-code";input.autocomplete="off";label.htmlFor=input.id;const result=el("p");result.setAttribute("role","status");const submit=el("button","Enter package code","primary");submit.type="submit";const cannot=el("button","I cannot find the code","secondary");cannot.type="button";form.append(label,input,submit,cannot,result);form.addEventListener("submit",e=>{e.preventDefault();if(lotCodeMatches(input.value,recall))renderStatus({status:"confirmed_match",recall,reason:"The entered package code matches the official recall record.",matchMethod:"package_code"});else{result.textContent="That code did not exactly match. This does not mean the product is safe; compare the official notice.";result.className="field-error";}});cannot.addEventListener("click",()=>{result.textContent="Do not assume the product is safe. Review the official notice or contact the manufacturer.";});box.append(form);}
  function appendRepeatActions(box){const a=el("div",null,"actions result-actions"),scan=el("button","Scan another product","primary"),manual=el("button","Enter another barcode","secondary");scan.type=manual.type="button";scan.addEventListener("click",()=>{resetCheck();startScanner();});manual.addEventListener("click",()=>{resetCheck();openManual();});a.append(scan,manual);box.append(a);}
  function renderStandaloneStatus(status,message){resetCheck(false);const outcome={status};const original=outcomeCopy[status][2];outcomeCopy[status][2]=message;renderStatus(outcome);outcomeCopy[status][2]=original;}
  function resetCheck(focusScan=true){stopScanner();$("lookup-progress").hidden=true;$("product-confirmation").hidden=true;$("results").hidden=true;$("product-summary").replaceChildren();$("result-panel").replaceChildren();$("barcode-input").value="";$("barcode-error").textContent="";$("continue-invalid").hidden=true;$("correction-actions").hidden=true;$("progress-announcement").textContent="";state.pendingBarcode="";state.pendingProduct=null;state.pendingOutcome=null;if(focusScan)$("scan-button").focus();}
  function openManual(){stopScanner();if($("scanner-dialog").open)$("scanner-dialog").close();$("manual-section").hidden=false;$("manual-button").setAttribute("aria-expanded","true");$("barcode-input").focus();}
  function submitBarcode(force=false){const code=normalizeBarcode($("barcode-input").value);$("continue-invalid").hidden=true;if(!isRecognizedLength(code)){ $("barcode-error").textContent="Enter 8, 12, 13, or 14 digits.";return;}if(!validateCheckDigit(code)&&!force){state.pendingBarcode=code;$("barcode-error").textContent="The check digit appears invalid. Correct the barcode or continue with a warning.";$("continue-invalid").hidden=false;return;}$("barcode-error").textContent="";checkProduct(code);}
  async function startScanner(){resetCheck(false);state.lastFocus=$("scan-button");const dialog=$("scanner-dialog");dialog.showModal();$("scanner-close").focus();if(!window.isSecureContext)return scannerError("Camera access requires HTTPS or localhost. Enter the barcode instead.");if(!navigator.mediaDevices?.getUserMedia)return scannerError("Camera access is unavailable. Enter the barcode instead.");if(!window.ZXingBrowser?.BrowserMultiFormatReader)return scannerError("The scanner could not load. Enter the barcode instead.");$("scanner-status").textContent="Requesting camera permission…";try{const reader=new window.ZXingBrowser.BrowserMultiFormatReader();state.scannerControls=await reader.decodeFromConstraints({audio:false,video:{facingMode:{ideal:"environment"}}},$("scanner-video"),(result,_error,controls)=>{if(result){const code=normalizeBarcode(result.getText());if(code&&code!==state.lastScan){state.lastScan=code;navigator.vibrate?.(60);try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();g.gain.value=.025;o.frequency.value=620;o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.06);}catch(_e){}controls.stop();stopScanner();dialog.close();checkProduct(code);}}});state.stream=$("scanner-video").srcObject;$("scanner-status").textContent="Camera active. Center the entire barcode and hold steady.";setupTorch();}catch(error){scannerError(error?.name==="NotAllowedError"?"Camera permission was denied. Allow it in browser settings or enter the barcode instead.":error?.name==="NotFoundError"?"No camera was found. Enter the barcode instead.":"The camera could not start. Try more light or enter the barcode instead.");}}
  function setupTorch(){const track=state.stream?.getVideoTracks?.()[0],caps=track?.getCapabilities?.();if(!caps?.torch)return;const b=$("torch-button");b.hidden=false;b.onclick=async()=>{const on=b.getAttribute("aria-pressed")!=="true";try{await track.applyConstraints({advanced:[{torch:on}]});b.setAttribute("aria-pressed",String(on));b.textContent=on?"Turn off flashlight":"Turn on flashlight";}catch(_e){b.hidden=true;}};}
  function scannerError(message){stopScanner();$("scanner-status").textContent=message;}
  function stopScanner(){if(state.scannerControls){state.scannerControls.stop();state.scannerControls=null;}const stream=state.stream||$("scanner-video")?.srcObject;stream?.getTracks().forEach(t=>t.stop());state.stream=null;if($("scanner-video"))$("scanner-video").srcObject=null;$("torch-button").hidden=true;}
  function closeScanner(){stopScanner();if($("scanner-dialog").open)$("scanner-dialog").close();$("scan-button").focus();}
  function bindEvents(){$("scan-button").addEventListener("click",startScanner);$("manual-button").addEventListener("click",openManual);$("scanner-close").addEventListener("click",closeScanner);$("scanner-stop").addEventListener("click",closeScanner);$("scanner-manual").addEventListener("click",()=>{closeScanner();openManual();});$("scanner-dialog").addEventListener("cancel",e=>{e.preventDefault();closeScanner();});$("barcode-form").addEventListener("submit",e=>{e.preventDefault();submitBarcode();});$("continue-invalid").addEventListener("click",()=>submitBarcode(true));$("confirm-product").addEventListener("click",continueConfirmedProduct);$("reject-product").addEventListener("click",()=>{$("correction-actions").hidden=false;});$("correction-manual").addEventListener("click",()=>{resetCheck(false);openManual();});$("correction-scan").addEventListener("click",startScanner);$("direct-check").addEventListener("click",continueConfirmedProduct);window.addEventListener("pagehide",stopScanner);document.addEventListener("visibilitychange",()=>{if(document.hidden)stopScanner();});}
  window.RecallCheck = Object.freeze({ normalizeBarcode, generateGtinVariants, validateCheckDigit, normalizeText, normalizeBrand, normalizePackageSize, exactCodeMatch, productNameTokenComparison, scoreRecall, classifyResult, lotCodeMatches, validateRecallData, dataAgeDays, isRecallDataUsable, identifyProductWithOpenFoodFacts });
  bindEvents(); loadData(); if ("serviceWorker" in navigator) navigator.serviceWorker.register("./sw.js").catch(() => {});
})();
