(() => {
  "use strict";
  const CONFIG = { recallUrl: "data/recalls.json", demoRecallUrl: "data/demo-recalls.json", demoUrl: "data/demo-products.json", offUrl: "https://world.openfoodfacts.org/api/v2/product/", timeout: 9000, staleDays: 8, version: "0.8", feedback: { mode: "disabled", endpoint: "", email: "CONFIGURE_FEEDBACK_EMAIL", timeout: 8000 } };
  const state = { recalls: null, demoRecalls: null, demos: [], scannerControls: null, stream: null, lastScan: "", pendingBarcode: "", lastFocus: null, feedbackSubmitting: false, feedbackSubmitted: false, feedbackOutcome: null, history: [], completedChecks: 0, installEvent: null, installDismissed: false, meaningfulInteraction: false };
  const $ = (id) => document.getElementById(id);
  const el = (tag, text, className) => { const node = document.createElement(tag); if (text != null) node.textContent = text; if (className) node.className = className; return node; };

  function normalizeBarcode(value) { return String(value ?? "").replace(/[\s-]/g, "").replace(/[^0-9]/g, ""); }
  function isRecognizedLength(code) { return [8, 12, 13, 14].includes(normalizeBarcode(code).length); }
  function validateCheckDigit(value) {
    const code = normalizeBarcode(value); if (!isRecognizedLength(code)) return false;
    const digits = [...code].map(Number); const supplied = digits.pop();
    const sum = digits.reverse().reduce((total, digit, i) => total + digit * (i % 2 === 0 ? 3 : 1), 0);
    return (10 - (sum % 10)) % 10 === supplied;
  }
  function generateGtinVariants(value) {
    const code = normalizeBarcode(value); const variants = new Set([code]);
    if (code.length === 12) { variants.add(`0${code}`); variants.add(`00${code}`); }
    if (code.length === 13) { variants.add(`0${code}`); if (code.startsWith("0")) variants.add(code.slice(1)); }
    if (code.length === 14) { if (code.startsWith("0")) variants.add(code.slice(1)); if (code.startsWith("00")) variants.add(code.slice(2)); }
    return [...variants].filter(Boolean);
  }
  function normalizeText(value) { return String(value ?? "").normalize("NFKD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim(); }
  function normalizeBrand(value) { return normalizeText(value).replace(/\b(inc|llc|company|co)\b/g, "").replace(/\s+/g, " ").trim(); }
  function normalizePackageSize(value) { return normalizeText(value).replace(/\bounces?\b/g, "oz").replace(/\bpounds?\b/g, "lb").replace(/\s+/g, ""); }
  function exactCodeMatch(code, recall) { const variants = new Set(generateGtinVariants(code)); return [...(recall.upcs || []), ...(recall.gtins || [])].some(item => generateGtinVariants(item).some(v => variants.has(v))); }
  const GENERIC_TERMS = new Set(["the","and","with","food","product","eggs","egg","milk","cheese","chicken","beef","bread","salad"]);
  function meaningfulTokens(value) { return normalizeText(value).split(" ").filter(t => t.length > 2 && !GENERIC_TERMS.has(t)); }
  function productNameTokenComparison(a, b) { const x = new Set(meaningfulTokens(a)); const y = new Set(meaningfulTokens(b)); if (!x.size || !y.size) return 0; return [...x].filter(t => y.has(t)).length / Math.max(x.size, y.size); }
  function recallLifecycle(recall) { const supplied=recall?.lifecycle; if(supplied && ["active","terminated","closed","unknown"].includes(supplied.state)) return supplied; const sourceStatus=String(recall?.status||""); const value=sourceStatus.toLowerCase(); const state=["ongoing","active","open","current"].includes(value)?"active":value==="terminated"?"terminated":["completed","closed"].includes(value)?"closed":"unknown"; return {state,isActionable:state==="active",sourceStatus,terminationDate:""}; }
  function scoreRecall(product, recall) {
    const raw = normalizeBarcode(product.code); const recallCodes = [...(recall.upcs || []), ...(recall.gtins || [])];
    const exact = recallCodes.some(code => normalizeBarcode(code) === raw);
    if (exactCodeMatch(product.code, recall)) return { score: 100, matchMethod: exact ? "exact_identifier" : "equivalent_gtin", matchedFields: [exact ? "barcode" : "equivalent GTIN"], exactBarcode: exact, equivalentBarcode: !exact, usedSimilarity: false, reason: `The ${exact ? "exact barcode" : "equivalent GTIN representation"} matches an identifier in the official record.` };
    const brand = (recall.brandNames || []).some(b => normalizeBrand(b) === normalizeBrand(product.brands));
    const name = Math.max(0, ...(recall.productNames || []).map(n => productNameTokenComparison(product.product_name, n)));
    const size = (recall.packageSizes || []).some(s => normalizePackageSize(s) === normalizePackageSize(product.quantity));
    const distinctiveName = name >= .5; const score = (brand ? 40 : 0) + Math.round(name * 45) + (size ? 15 : 0);
    const matchedFields = [brand && "brand", distinctiveName && "distinctive product name", size && "package size"].filter(Boolean);
    return { score, matchMethod: "product_similarity", matchedFields, exactBarcode: false, equivalentBarcode: false, usedSimilarity: true, reason: matchedFields.length ? `Similar product details: ${matchedFields.join(", ")}.` : "Related wording in the recall record." };
  }
  function classifyResult(product, recalls) {
    const candidates=recalls.map(recall=>{const match=scoreRecall(product,recall), lifecycle=recallLifecycle(recall); const historical=["closed","terminated"].includes(lifecycle.state); const strongSimilarity=match.usedSimilarity&&match.score>=70&&match.matchedFields.length>=2&&(match.matchedFields.includes("brand")||match.matchedFields.includes("distinctive product name")); let priority=0; if(!match.usedSimilarity) priority=historical?400:(lifecycle.state==="active"?(match.exactBarcode?800:600):(match.exactBarcode?700:500)); else if(strongSimilarity) priority=historical?300:lifecycle.state==="active"?450:250; return {...match,recall,lifecycle,strongSimilarity,priority};}).filter(x=>x.priority).sort((a,b)=>b.priority-a.priority||b.score-a.score);
    const secondary=candidates.filter(x=>["closed","terminated","unknown"].includes(x.lifecycle.state)&&x.strongSimilarity); const best=candidates[0];
    if(!best) return {status:"no_matching_current_recall",historicalRecords:secondary};
    if(!best.usedSimilarity){ if(["closed","terminated"].includes(best.lifecycle.state)) return {status:"historical_exact_match",...best,historicalRecords:secondary.filter(x=>x!==best)}; if(best.lifecycle.state==="unknown") return {status:"current_recall_manual_review",...best,reason:"The barcode matches an official record, but its current lifecycle status could not be confirmed."}; const unresolved=[...(best.recall.lotCodes||[]).map(()=>"lot code"),...(best.recall.dateCodes||[]).map(()=>"date code")]; return unresolved.length?{status:"current_recall_details_required",unresolvedDetails:unresolved,...best}:{status:"confirmed_current_recall",...best}; }
    return {status:"current_recall_manual_review",...best,historicalRecords:secondary};
  }
  function lotCodeMatches(input, recall) { const value = normalizeText(input).replace(/\s/g, ""); return [...(recall.lotCodes || []), ...(recall.dateCodes || [])].some(code => normalizeText(code).replace(/\s/g, "") === value); }
  function validateRecallData(data) { return Boolean(data && typeof data.generatedAt === "string" && Array.isArray(data.sources) && Array.isArray(data.recalls)); }
  function dataAgeDays(generatedAt, now = Date.now()) { const time = Date.parse(generatedAt); return Number.isFinite(time) ? Math.max(0, Math.floor((now - time) / 86400000)) : Infinity; }
  function isRecallDataUsable(data) { return validateRecallData(data) && Boolean(data.dataHealth) && Object.values(data.dataHealth.sources || {}).some(source => source.success || source.recordCount > 0); }

  async function loadJson(url) { const response = await fetch(url); if (!response.ok) throw new Error(`Request failed (${response.status})`); return response.json(); }
  async function loadData() {
    const results = await Promise.allSettled([loadJson(CONFIG.recallUrl), loadJson(CONFIG.demoUrl), loadJson(CONFIG.demoRecallUrl)]);
    if (results[0].status === "fulfilled" && validateRecallData(results[0].value)) { state.recalls = results[0].value; const when = new Date(state.recalls.generatedAt); const date = when.toLocaleString(); const today = new Date().toDateString() === when.toDateString(); const usable = isRecallDataUsable(state.recalls); $("data-notice").textContent = usable ? (today ? "Recall data updated today" : `Recall data last updated ${when.toLocaleDateString()}`) : "Official recall coverage is currently unavailable"; $("footer-updated").textContent = `Recall data last updated ${date}.`; renderDataStatus(state.recalls); } else { $("data-notice").textContent = "Official recall coverage could not be loaded"; renderDataStatus(null); }
    if (results[1].status === "fulfilled" && Array.isArray(results[1].value.products)) state.demos = results[1].value.products;
    if (results[2].status === "fulfilled" && validateRecallData(results[2].value)) state.demoRecalls = results[2].value;
    renderDemos();
  }
  function formatSourceError(error) { if (!error) return ""; if (typeof error === "string") return error; const prefix = error.httpStatus != null ? `HTTP ${error.httpStatus}` : (error.type || "Request error"); return `${prefix}${error.message || error.httpReason ? ` — ${error.message || error.httpReason}` : ""}`; }
  function renderDataStatus(data) { const root = $("data-status-content"); root.replaceChildren(); if (!data?.dataHealth) { root.append(el("p", "Recall data coverage details are unavailable.")); return; } const health=data.dataHealth, age=dataAgeDays(data.generatedAt); ["FDA","USDA"].forEach(agency=>{const source=health.sources?.[agency]||{};root.append(el("p",`${agency === "FDA" ? "FDA food" : "USDA meat and poultry"} recall data is ${source.success || source.recordCount > 0 ? "available" : "unavailable"}.`));}); root.append(el("p",`Recall data was last updated ${new Date(data.generatedAt).toLocaleString()}.`)); const technical=el("details",null,"technical"),summary=el("summary","Technical details"),body=el("div"); body.append(el("p",`Data age: ${Number.isFinite(age)?`${age} day${age===1?"":"s"}`:"unknown"}. Last successful update: ${health.lastSuccessfulUpdate?new Date(health.lastSuccessfulUpdate).toLocaleString():"not recorded"}.`)); ["FDA","USDA"].forEach(agency=>{const source=health.sources?.[agency]||{},error=formatSourceError(source.error);body.append(el("p",`${agency}: ${source.recordCount||0} records${error?` · ${error}`:""}`));}); (health.warnings||[]).forEach(w=>body.append(el("p",w,"field-error"))); technical.append(summary,body); root.append(technical); }
  function renderDemos() { const list = $("demo-list"); list.replaceChildren(); list.setAttribute("aria-busy", "false"); if (!state.demos.length) { list.append(el("p", "Demo products could not be loaded.")); return; } state.demos.forEach(demo => { const button = el("button", null, "demo-card"); button.type = "button"; button.append(el("strong", demo.label), el("span", demo.description)); button.addEventListener("click", () => checkProduct(demo.code, { demo })); list.append(button); }); }

  async function identifyProductWithOpenFoodFacts(code, options = {}) {
    if (options.demo) return options.demo.product || null;
    const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), options.timeout ?? CONFIG.timeout); const fetcher = options.fetchImpl || fetch;
    try { const fields = "code,product_name,generic_name,brands,quantity,image_front_small_url,categories,countries,manufacturing_places,owner_fields"; const response = await fetcher(`${CONFIG.offUrl}${encodeURIComponent(code)}.json?fields=${fields}`, { signal: controller.signal, headers: { "Accept": "application/json", "X-Requested-With": "RecallCheck" } }); if (response.status === 429) throw new Error("rate_limit"); if (!response.ok) throw new Error("service"); const body = await response.json(); if (!body || typeof body.status !== "number") throw new Error("malformed"); return body.status === 1 && body.product ? body.product : null; } catch (error) { if (error.name === "AbortError") throw new Error("timeout"); throw error; } finally { clearTimeout(timer); }
  }
  function setProgress(step, productFound = true) {
    $("lookup-progress").hidden = false;
    const items = [$("progress-barcode"), $("progress-product"), $("progress-recalls")];
    items.forEach((item, i) => { item.className = i < step ? "done" : i === step ? "active" : ""; });
    if (step === 0) $("progress-announcement").textContent = "Barcode captured. Identifying product.";
    if (step === 1) $("progress-announcement").textContent = `${productFound ? "Product identified" : "Product information not found"}. Checking FDA and USDA recalls.`;
  }
  function sourceAvailability(dataset) { return ["FDA", "USDA"].filter(a => dataset?.dataHealth?.sources?.[a]?.success || dataset?.dataHealth?.sources?.[a]?.recordCount > 0); }
  function makeProductCard(product) { const wrap = el("article", null, "product"); let image; if (product.image_front_small_url) { image = el("img"); image.src = product.image_front_small_url; image.alt = `${product.product_name || "Product"} package`; image.referrerPolicy = "no-referrer"; } else { image = el("div", "▧", "image-placeholder"); image.setAttribute("role", "img"); image.setAttribute("aria-label", "Product image unavailable"); } const info = el("div"); info.append(el("h3", product.product_name || product.generic_name || "Name unavailable"), el("p", `Brand: ${product.brands || "Unavailable"}`), el("p", `Package size: ${product.quantity || "Unavailable"}`), el("p", `Barcode: ${product.code}`)); wrap.append(image, info); return wrap; }
  async function checkProduct(rawCode, options = {}) {
    const code = normalizeBarcode(rawCode); if (!isRecognizedLength(code)) return renderStandaloneStatus("invalid_barcode", "Enter an 8, 12, 13, or 14-digit barcode.");
    stopScanner(); resetCheck(false); setProgress(0); state.pendingBarcode = code;
    let product = null, productError = "";
    try { product = await identifyProductWithOpenFoodFacts(code, options); } catch (error) { productError = error.message; }
    setProgress(1, Boolean(product)); await new Promise(resolve => setTimeout(resolve, options.demo ? 50 : 180));
    const dataset = options.demo ? state.demoRecalls : state.recalls;
    if (!dataset || (!options.demo && !isRecallDataUsable(dataset))) { $("lookup-progress").hidden = true; renderStatus({ status:"recall_data_unavailable", productServiceUnavailable:Boolean(productError), isDemo:Boolean(options.demo) }); return; }
    const direct = dataset.recalls.filter(r => exactCodeMatch(code, r));
    if (!product) { $("lookup-progress").hidden = true; if (direct.length) return renderStatus({ ...classifyResult({code,product_name:"",brands:"",quantity:""}, direct), isDemo:Boolean(options.demo), productIdentityMissing:true, productServiceUnavailable:Boolean(productError) }); return renderStatus({ status:"no_matching_current_recall", productIdentityMissing:true, isDemo:Boolean(options.demo), productServiceUnavailable:Boolean(productError), matchMethod:"direct_barcode_check", matchedFields:[] }); }
    product.code = code; state.pendingProduct = product; state.pendingOptions = options;
    const outcome = options.demo?.forcedStatus ? { status:options.demo.forcedStatus, recall:dataset.recalls.find(r=>r.id===options.demo.recallId), reason:options.demo.reason, matchMethod:"demo_scenario", matchedFields:["fictional demo setup"], exactBarcode:options.demo.forcedStatus!=="possible_match_manual_review", usedSimilarity:options.demo.forcedStatus==="possible_match_manual_review" } : classifyResult(product,dataset.recalls);
    outcome.isDemo=Boolean(options.demo); const checked=sourceAvailability(dataset); if(checked.length===1 && outcome.status==="no_matching_current_recall") outcome.status="partial_recall_check"; state.pendingOutcome=outcome; $("lookup-progress").hidden=true;
    if (["confirmed_current_recall","current_recall_details_required","historical_exact_match"].includes(outcome.status)) { renderProduct(product); renderStatus(outcome); return; }
    $("confirmation-product").replaceChildren(makeProductCard(product)); $("product-confirmation").hidden=false; $("confirmation-title").focus?.();
  }
  function continueConfirmedProduct() { $("product-confirmation").hidden=true; renderProduct(state.pendingProduct); renderStatus(state.pendingOutcome); }
  function renderProduct(product) { const correction=el("button","Not my product","text-button"); correction.type="button"; correction.addEventListener("click",()=>{ $("results").hidden=true; $("confirmation-product").replaceChildren(makeProductCard(product)); $("product-confirmation").hidden=false; $("correction-actions").hidden=false; }); $("product-summary").replaceChildren(makeProductCard(product), el("p", "Product information supplied by Open Food Facts and may be incomplete.", "coverage-line"), correction); }
  const RESULT_COPY = {
    confirmed_current_recall:{label:"Current recall",heading:"This product is connected to a current recall",instruction:"Do not eat or serve this product until you review the official recall instructions.",tone:"critical",icon:"critical"},
    current_recall_details_required:{label:"Current recall",heading:"This barcode is associated with a current recall",instruction:"Do not eat or serve the product until you confirm whether your package is included.",tone:"critical",icon:"critical"},
    current_recall_manual_review:{label:"Official recall match",heading:"This barcode appears in an official recall record",instruction:"RecallCheck could not confirm whether the recall is still active. Review the dated official notice before using the product.",tone:"warning-critical",icon:"verification"},
    historical_exact_match:{label:"Historical recall",heading:"This barcode appears in an older recall record",instruction:"The official record is listed as closed or terminated. Your current package is not being identified as part of an active recall.",tone:"historical",icon:"archive"},
    no_matching_current_recall:{label:"No current match found",heading:"No matching current recall was found",instruction:"This is not a safety guarantee. Some recall notices do not include barcodes, and recall information can change.",tone:"neutral-result",icon:"information"},
    partial_recall_check:{label:"Partial recall check",heading:"Only part of the official recall data could be checked",instruction:"A complete no-match conclusion cannot be made. Check the unavailable agency directly.",tone:"warning",icon:"verification"},
    recall_data_unavailable:{label:"Check not completed",heading:"FDA and USDA recall records could not be checked",instruction:"Do not rely on this page to determine whether the product is recalled.",tone:"failure",icon:"unavailable"}
  };
  const ICON_PATHS={critical:'<path d="M12 3 2.8 20h18.4L12 3Z"/><path d="M12 9v5m0 3h.01"/>',verification:'<circle cx="12" cy="12" r="9"/><path d="M12 7v6m0 4h.01"/>',information:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10h.01"/>',archive:'<path d="M4 7h16v13H4zM3 4h18v3H3z"/><path d="M9 11h6"/>',unavailable:'<path d="M5 5l14 14M8 4h8l4 4v12H7a3 3 0 0 1-3-3V8"/>',barcode:'<path d="M4 5v14m3-14v14m4-14v14m5-14v14m3-14v14"/>',check:'<path d="m4 12 5 5L20 6"/>',share:'<circle cx="18" cy="5" r="2"/><circle cx="6" cy="12" r="2"/><circle cx="18" cy="19" r="2"/><path d="m8 11 8-5m-8 7 8 5"/>',external:'<path d="M14 4h6v6m0-6-9 9"/><path d="M19 13v7H4V5h7"/>'};
  function icon(name){const svg=document.createElementNS("http://www.w3.org/2000/svg","svg");svg.setAttribute("viewBox","0 0 24 24");svg.setAttribute("class","icon icon--"+name);svg.setAttribute("aria-hidden","true");svg.setAttribute("focusable","false");svg.setAttribute("fill","none");svg.setAttribute("stroke","currentColor");svg.setAttribute("stroke-width","2");svg.insertAdjacentHTML("afterbegin",ICON_PATHS[name]||ICON_PATHS.information);return svg;}
  function actionLink(label,url,kind="secondary"){const a=el("a",label,`button button--${kind}`);a.href=url;if(url.startsWith("http")){a.target="_blank";a.rel="noopener noreferrer";a.append(icon("external"));}return a;}
  function addOfficialLinks(box){const actions=el("div",null,"result-actions");actions.append(actionLink("Search FDA recalls","https://www.fda.gov/safety/recalls-market-withdrawals-safety-alerts","secondary"),actionLink("Search USDA recalls","https://www.fsis.usda.gov/recalls","secondary"));box.append(actions);}
  function renderStatus(outcome){const spec=RESULT_COPY[outcome.status]||RESULT_COPY.current_recall_manual_review;const box=el("article",null,`result result--${spec.tone}`);if(["confirmed_current_recall","current_recall_details_required","recall_data_unavailable"].includes(outcome.status))box.setAttribute("role","alert");const banner=el("header",null,`result-banner result-banner--${spec.tone}`),copy=el("div");copy.append(el("p",spec.label,"result-label"));const heading=el("h2",spec.heading,"result-heading");heading.id="completed-result-heading";heading.tabIndex=-1;copy.append(heading);banner.append(icon(spec.icon),copy);const summary=el("section",null,"result-summary");summary.append(el("p",spec.instruction,"result-instruction"));box.append(banner,summary);const dataset=outcome.isDemo?state.demoRecalls:state.recalls,available=sourceAvailability(dataset);
    if(outcome.productIdentityMissing){const identity=el("aside",null,"product-identity");identity.append(icon("barcode"),el("h3","Product name not found"),el("p","We could not identify the product through Open Food Facts. We still checked the barcode against official recall records."));box.prepend(identity);}
    if(outcome.status==="no_matching_current_recall")summary.prepend(el("p","RecallCheck did not find this barcode in the current FDA or USDA recall records available."));
    if(outcome.status==="partial_recall_check"){const missing=["FDA","USDA"].filter(a=>!available.includes(a));summary.append(el("p",`Checked: ${available.join(" and ")}. Unavailable: ${missing.join(" and ")}. No exact match was found in the available source.`));summary.append(actionLink(`Check ${missing.join(" and ")} directly`,missing[0]==="FDA"?"https://www.fda.gov/safety/recalls-market-withdrawals-safety-alerts":"https://www.fsis.usda.gov/recalls","warning"));}
    if(outcome.status==="recall_data_unavailable")addOfficialLinks(summary);
    if(outcome.recall)appendRecallDetails(box,outcome.recall,outcome.status,dataset,outcome);
    if(outcome.historicalRecords?.length){const d=el("details",null,"historical-records"),sum=el("summary","Older or similar recall records found");d.append(sum);outcome.historicalRecords.forEach(record=>{const card=el("article",null,"similar-historical");card.append(el("h3","Similar historical recall"),el("p","Your barcode does not match this official record. This is not evidence that your package is recalled."));appendRecallDetails(card,record.recall,"historical_similar_record",dataset,record);d.append(card);});box.append(d);}
    appendTrustSummary(box,outcome,dataset,available);appendTransparency(box,outcome);appendFeedback(box,outcome);appendRepeatActions(box,outcome);$("result-panel").replaceChildren(box);$("results").hidden=false;addSessionHistory(outcome);heading.focus();}
  function appendTrustSummary(box,outcome,dataset,available){const panel=el("section",null,"trust-summary");panel.append(el("h3","How this result was determined"));const dl=el("dl",null,"details"),status=outcome.lifecycle?.sourceStatus||outcome.recall?.status||"Not applicable";[["Agencies checked",available.join(" and ")||"None"],["Recall data updated",dataset?.generatedAt?new Date(dataset.generatedAt).toLocaleString():"Unavailable"],["Barcode match",outcome.exactBarcode?"Exact":outcome.equivalentBarcode?"Equivalent product number":outcome.recall?"Not exact":"No"],["Official status",status],["Package confirmation",outcome.unresolvedDetails?.length?"Still required":outcome.recall?"No restriction unresolved":"Not applicable"],["Product information source",outcome.isDemo?"Fictional Demo Mode":outcome.productIdentityMissing?"Name unavailable; official barcode check completed":"Open Food Facts"]].forEach(([a,b])=>dl.append(el("dt",a),el("dd",b)));panel.append(dl);box.append(panel);}
  function appendTransparency(box,outcome){const d=el("details",null,"transparency");d.append(el("summary","Why am I seeing this?"));const messages={confirmed_current_recall:"The barcode matches a product number in the official recall notice.",current_recall_details_required:"The barcode matches the official notice, but the notice limits affected packages.",historical_exact_match:"The barcode matches an older record that the agency lists as closed or terminated.",no_matching_current_recall:"RecallCheck did not find an exact current barcode match in the available official records."};d.append(el("p",messages[outcome.status]||outcome.reason||"Available agency records determined this result."));if(outcome.matchMethod){const tech=el("details",null,"technical");tech.append(el("summary","Technical details"),el("p",`Match method: ${outcome.matchMethod}. Matched fields: ${(outcome.matchedFields||[]).join(", ")||"none"}.`));d.append(tech);}box.append(d);}
  function formatDate(value){const date=Date.parse(value);return Number.isFinite(date)?new Intl.DateTimeFormat("en-US",{year:"numeric",month:"long",day:"numeric",timeZone:"UTC"}).format(date):"Not listed";}
  function classificationGuidance(value){const copy={"Class I":["Highest FDA recall risk category","A reasonable chance exists that use or exposure could cause serious health consequences or death."],"Class II":["Moderate FDA recall risk category","Use or exposure may cause temporary or medically reversible effects, or serious effects are unlikely."],"Class III":["Lowest FDA recall risk category","Use or exposure is unlikely to cause adverse health consequences."]};if(!copy[value])return null;const s=el("aside",null,"classification-guidance");s.append(el("h3","FDA classification guidance"),el("strong",`${value}: ${copy[value][0]}`),el("p",copy[value][1]));return s;}
  function appendRecallDetails(box,recall,status,dataset,outcome={}){const lifecycle=recallLifecycle(recall),historical=["closed","terminated"].includes(lifecycle.state),restrictions=[...(recall.lotCodes||[]),...(recall.dateCodes||[]),...(recall.packageSizes||[]),...(recall.establishmentNumbers||[])],section=el("section",null,"result-details"),dl=el("dl",null,"details");[["Agency",recall.agency],["Recall date",formatDate(recall.timeline?.recallDate||recall.recallDate)],["Recall reason",recall.reason],["Recalling company",recall.recallingFirm],["Barcode match",outcome.exactBarcode?"Exact":outcome.equivalentBarcode?"Equivalent product number":"Not exact"],["Current status",lifecycle.sourceStatus||"Could not be confirmed"],["Termination date",historical?formatDate(lifecycle.terminationDate):null],["Affected package information",restrictions.join(", ")||"No package restriction listed"]].filter(([,v])=>v!=null).forEach(([a,b])=>dl.append(el("dt",a),el("dd",b||"Not listed")));section.append(dl);const guide=recall.agency==="FDA"&&classificationGuidance(recall.classification);if(guide)section.append(guide);const official=window.RecallDiscovery?.safeOfficialUrl(recall.officialUrl)||"";if(official)section.append(actionLink(historical?"View historical recall":"View official recall instructions",official,historical?"secondary":status==="current_recall_manual_review"?"warning":"critical"));box.append(section);if(status==="current_recall_details_required")appendLotForm(box,recall);}
  function codeHelp(){const aside=el("aside",null,"code-help");aside.append(el("h4","Where to find it"),el("p","Look on the top seal, bottom panel, side seam, cap, near the barcode or nutrition label, or in the establishment number area."));return aside;}
  function packageOutcome(panel,tone,heading,instruction){const out=el("div",null,`package-outcome package-outcome--${tone}`);out.setAttribute("role","status");out.append(el("h4",heading),el("p",instruction));panel.querySelector(".package-outcome")?.remove();panel.append(out);}
  function appendLotForm(box,recall){const panel=el("section",null,"package-verification package-verification--warning");panel.append(icon("verification"),el("p","Check your package","result-label"),el("h3","Check whether your package is included"));const values=[...(recall.lotCodes||[]),...(recall.dateCodes||[]),...(recall.establishmentNumbers||[])];const dl=el("dl",null,"details");dl.append(el("dt","Look for"),el("dd",recall.dateCodes?.length?"Printed date":recall.establishmentNumbers?.length?"Establishment number":"Lot code"),el("dt","Affected value"),el("dd",values.join(", ")||"See official notice"));panel.append(dl,codeHelp());const choices=el("div",null,"verification-actions");[["My package matches","match"],["My package does not match","no-match"],["I cannot find the code","unknown"]].forEach(([label,value])=>{const b=el("button",label,value==="match"?"button button--critical":"button button--secondary");b.type="button";b.addEventListener("click",()=>value==="match"?packageOutcome(panel,"critical","Your package appears to be included in the recall","Do not eat or serve this product. Follow the official recall instructions."):value==="no-match"?packageOutcome(panel,"neutral","The package information you entered does not match the listed recalled packages","This does not guarantee the product is safe. Review the official notice if you are unsure."):packageOutcome(panel,"warning","We cannot determine whether your package is included","Do not assume the product is unaffected. Review the official notice or contact the manufacturer."));choices.append(b);});panel.append(choices);if(values.length){const form=el("form",null,"lot-form"),label=el("label","Enter a package code"),input=el("input");input.id="package-code";input.autocomplete="off";label.htmlFor=input.id;const submit=el("button","Check entered code","button button--warning");submit.type="submit";form.append(label,input,submit);form.addEventListener("submit",e=>{e.preventDefault();const shown=input.value.trim();packageOutcome(panel,lotCodeMatches(shown,recall)?"critical":"neutral",lotCodeMatches(shown,recall)?"Your package appears to be included in the recall":"The package information you entered does not match the listed recalled packages",lotCodeMatches(shown,recall)?"Do not eat or serve this product. Follow the official recall instructions.":`You entered “${shown}.” This does not guarantee the product is safe. Review the official notice if you are unsure.`);});panel.append(form);}box.append(panel);}
  const FEEDBACK_REASONS = {
    helpful: ["Result was clear", "Next steps were useful", "Product match looked correct", "Recall status was easy to understand", "Official source was helpful"],
    confusing: ["Wrong product", "Recall seemed unrelated", "Current versus historical was unclear", "Official link was not helpful", "I could not find the lot code", "Result took too long", "Scanner did not work", "Something else"]
  };
  function validFeedbackEndpoint() { try { const url=new URL(CONFIG.feedback.endpoint); return url.protocol==="https:"&&!url.username&&!url.password&&!url.search&&!url.hash; } catch(_error){ return false; } }
  function feedbackMode() { const f=CONFIG.feedback; if(f.mode==="endpoint"&&validFeedbackEndpoint())return "endpoint"; if((f.mode==="email"||f.mode==="endpoint")&&f.email&&f.email!=="CONFIGURE_FEEDBACK_EMAIL"&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(f.email))return "email"; return "disabled"; }
  function safeFeedbackContext(outcome) { const dataset=outcome.isDemo?state.demoRecalls:state.recalls; const status=String(outcome.status||"unknown").slice(0,80); return { resultState:status, classification:status.startsWith("historical")?"historical":status.includes("current")||status==="confirmed_current_recall"?"current":"none_or_unavailable", agencyCoverage:sourceAvailability(dataset), matchCategory:outcome.exactBarcode||outcome.equivalentBarcode?"exact_or_equivalent":outcome.usedSimilarity?"similarity":"none", applicationVersion:CONFIG.version, browserLanguage:String(navigator.language||"").slice(0,35), isDemo:Boolean(outcome.isDemo) }; }
  function buildFeedbackPayload(value,reason,comment,outcome=state.feedbackOutcome) { if(!["helpful","confusing"].includes(value))return null; const context=safeFeedbackContext(outcome||{}); return { feedback:value, reason:FEEDBACK_REASONS[value].includes(reason)?reason:"", comment:String(comment||"").trim().slice(0,750), ...context, submissionTimestamp:new Date().toISOString() }; }
  function feedbackMailto(payload) { const lines=[`Feedback: ${payload.feedback}`,`Reason: ${payload.reason||"Not selected"}`,`Comment: ${payload.comment||"Not provided"}`,`Result state: ${payload.resultState}`,`Application version: ${payload.applicationVersion}`]; return `mailto:${encodeURIComponent(CONFIG.feedback.email)}?subject=${encodeURIComponent("RecallCheck feedback")}&body=${encodeURIComponent(lines.join("\n"))}`; }
  function configureFeedback(next={}) { Object.assign(CONFIG.feedback,next); }
  function appendFeedback(box,outcome){state.feedbackOutcome=outcome;state.feedbackSubmitted=false;const section=el("section",null,"feedback");section.setAttribute("aria-labelledby","feedback-title");const title=el("h3","Was this result helpful or confusing?");title.id="feedback-title";const choices=el("div",null,"feedback-choices");const live=el("p",null,"feedback-live");live.setAttribute("role","status");live.setAttribute("aria-live","polite");["helpful","confusing"].forEach(value=>{const b=el("button",value[0].toUpperCase()+value.slice(1),"secondary feedback-choice");b.type="button";b.setAttribute("aria-pressed","false");b.addEventListener("click",()=>expandFeedback(section,value,outcome,b));choices.append(b);});section.append(title,choices,el("p","Feedback does not include your barcode, product details, camera images, or personal information unless you type personal information into the optional comment. Please do not include sensitive information.","feedback-privacy"));if(outcome.isDemo)section.append(el("p","This feedback is about a fictional Demo Mode result.","instruction"));section.append(live);box.append(section);}
  function expandFeedback(section,value,outcome,selected){section.querySelectorAll(".feedback-choice").forEach(b=>b.setAttribute("aria-pressed",String(b===selected)));section.querySelector(".feedback-form")?.remove();const form=el("form",null,"feedback-form");const follow=el("h4",value==="helpful"?"Thanks—your feedback helps ITSBAD LLC improve RecallCheck.":"Thanks for letting us know. What was confusing?");follow.tabIndex=-1;form.append(follow);const fieldset=el("fieldset"),legend=el("legend",value==="helpful"?"What was most helpful? (optional)":"Choose a reason (optional)");fieldset.append(legend);FEEDBACK_REASONS[value].forEach((reason,i)=>{const label=el("label",null,"feedback-reason"),input=el("input");input.type="radio";input.name="feedback-reason";input.value=reason;input.id=`feedback-${value}-${i}`;label.htmlFor=input.id;label.append(input,document.createTextNode(reason));fieldset.append(label);});form.append(fieldset);let comment=null;if(value==="confusing"){const label=el("label","Tell us more (optional)"),help=el("small","750 characters maximum. 750 remaining.");help.id="feedback-comment-help";help.setAttribute("aria-live","polite");comment=el("textarea");comment.id="feedback-comment";comment.maxLength=750;comment.rows=4;comment.setAttribute("aria-describedby","feedback-comment-help feedback-privacy-reminder");label.htmlFor=comment.id;const reminder=el("p","Do not include personal, medical, or sensitive information.","feedback-privacy");reminder.id="feedback-privacy-reminder";comment.addEventListener("input",()=>{help.textContent=`750 characters maximum. ${750-comment.value.length} remaining.`;});form.append(label,comment,help,reminder);}const mode=feedbackMode();if(mode==="endpoint"){const origin=new URL(CONFIG.feedback.endpoint).origin;form.append(el("p",`Feedback is sent to the configured service at ${origin}. RecallCheck does not intentionally include product identifiers or personal information. The receiving service may process basic network information required to deliver the submission.`,"feedback-privacy"));}const actions=el("div",null,"actions");if(mode!=="disabled"){const submit=el("button",mode==="endpoint"?"Submit feedback":"Send feedback to ITSBAD LLC","primary");submit.type="submit";actions.append(submit);}else form.append(el("p","Your selection is acknowledged on this device only; feedback is not transmitted.","feedback-local"));const skip=el("button","Continue without sending","text-button");skip.type="button";skip.addEventListener("click",()=>showFeedbackThanks(section,false));actions.append(skip);form.append(actions);form.addEventListener("submit",e=>submitFeedback(e,section,value,outcome,comment));section.append(form);follow.focus();}
  async function submitFeedback(event,section,value,outcome,comment){event.preventDefault();if(state.feedbackSubmitting||state.feedbackSubmitted)return;const reason=section.querySelector('input[name="feedback-reason"]:checked')?.value||"";const payload=buildFeedbackPayload(value,reason,comment?.value,outcome);if(!payload)return;const mode=feedbackMode();if(mode==="email"){window.location.href=feedbackMailto(payload);section.querySelector(".feedback-live").textContent="Your email application has been opened. Feedback is sent only if you send the message.";return;}if(mode!=="endpoint")return;state.feedbackSubmitting=true;const submit=section.querySelector('button[type="submit"]');if(submit)submit.disabled=true;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),CONFIG.feedback.timeout);try{const response=await fetch(CONFIG.feedback.endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload),signal:controller.signal,credentials:"omit",referrerPolicy:"no-referrer"});if(!response.ok)throw new Error("failed");state.feedbackSubmitted=true;showFeedbackThanks(section,true);}catch(_error){showFeedbackFailure(section,value,outcome,comment);}finally{clearTimeout(timer);state.feedbackSubmitting=false;if(submit)submit.disabled=false;}}
  function showFeedbackThanks(section,submitted){section.replaceChildren();const h=el("h3",submitted?"Thank you for helping ITSBAD LLC improve RecallCheck.":"Thanks—your choice was not transmitted.");h.tabIndex=-1;const again=el("button","Check another product","primary");again.type="button";again.addEventListener("click",()=>{resetCheck(false);openManual();});section.append(h,again);h.focus();}
  function showFeedbackFailure(section,value,outcome,comment){const old=section.querySelector(".feedback-error");old?.remove();const error=el("div",null,"feedback-error");error.setAttribute("role","alert");error.append(el("p","Your feedback could not be sent.","field-error"));const retry=el("button","Try again","primary");retry.type="button";retry.addEventListener("click",()=>section.querySelector(".feedback-form")?.requestSubmit());error.append(retry);if(CONFIG.feedback.email&&CONFIG.feedback.email!=="CONFIGURE_FEEDBACK_EMAIL"){const email=el("a","Use email instead","secondary");email.href=feedbackMailto(buildFeedbackPayload(value,section.querySelector('input[name="feedback-reason"]:checked')?.value||"",comment?.value,outcome));error.append(email);}const continueButton=el("button","Continue without sending","text-button");continueButton.type="button";continueButton.addEventListener("click",()=>showFeedbackThanks(section,false));error.append(continueButton);section.append(error);retry.focus();}
  function appendRepeatActions(box,outcome){const a=el("div",null,"actions result-actions"),scan=el("button","Check Another Product","button button--primary");scan.type="button";scan.addEventListener("click",()=>{state.meaningfulInteraction=true;maybeShowInstall();resetCheck();startScanner();});a.append(scan);if(outcome.recall){const share=el("a","Share this recall","button button--secondary");share.href=`recall.html?id=${encodeURIComponent(outcome.recall.id)}`;a.append(share);}box.append(a);}
  function addSessionHistory(outcome){if(outcome.isDemo)return;state.completedChecks++;state.history.unshift({label:`Product check ${state.completedChecks}`,status:(RESULT_COPY[outcome.status]||{}).label||"Result",classification:outcome.status.startsWith("historical")?"Historical":outcome.status.includes("current")?"Current":"Other",time:new Date().toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})});state.history=state.history.slice(0,5);renderHistory();if(state.completedChecks>=2)maybeShowInstall();}
  function renderHistory(){const panel=$("session-history"),list=$("session-history-list");if(!panel||!list)return;panel.hidden=!state.history.length;list.replaceChildren(...state.history.map(item=>{const li=el("li");li.append(el("strong",item.label),document.createTextNode(` — ${item.status} · ${item.classification} · ${item.time}`));return li;}));}
  function maybeShowInstall(){if(!state.installEvent||state.installDismissed||matchMedia("(display-mode: standalone)").matches||!state.meaningfulInteraction&&state.completedChecks<2)return;$("install-prompt").hidden=false;}
  function renderStandaloneStatus(_status,message){resetCheck(false);openManual();const input=$("barcode-input"),error=$("barcode-error");input.setAttribute("aria-invalid","true");error.textContent=`Check the barcode number. ${message}`;input.focus();}
  function resetCheck(focusScan=true){stopScanner();$("lookup-progress").hidden=true;$("product-confirmation").hidden=true;$("results").hidden=true;$("product-summary").replaceChildren();$("result-panel").replaceChildren();$("barcode-input").value="";$("barcode-error").textContent="";$("barcode-input").removeAttribute("aria-invalid");$("continue-invalid").hidden=true;$("correction-actions").hidden=true;$("progress-announcement").textContent="";state.pendingBarcode="";state.pendingProduct=null;state.pendingOutcome=null;state.feedbackSubmitting=false;state.feedbackSubmitted=false;state.feedbackOutcome=null;if(focusScan)$("scan-button").focus();}
  function openManual(){stopScanner();if($("scanner-dialog").open)$("scanner-dialog").close();$("manual-section").hidden=false;$("manual-button").setAttribute("aria-expanded","true");$("barcode-input").focus();}
  function submitBarcode(force=false){const code=normalizeBarcode($("barcode-input").value);$("continue-invalid").hidden=true;if(!isRecognizedLength(code)){ $("barcode-input").setAttribute("aria-invalid","true");$("barcode-error").textContent="Check the barcode number. Enter the 8, 12, 13, or 14 digits printed below the barcode.";$("barcode-input").focus();return;}if(!validateCheckDigit(code)&&!force){state.pendingBarcode=code;$("barcode-error").textContent="The check digit appears invalid. Correct the barcode or continue with a warning.";$("continue-invalid").hidden=false;return;}$("barcode-error").textContent="";$("barcode-input").removeAttribute("aria-invalid");checkProduct(code);}
  async function startScanner(){resetCheck(false);state.lastFocus=$("scan-button");const dialog=$("scanner-dialog");dialog.showModal();$("scanner-close").focus();if(!window.isSecureContext)return scannerError("Camera access requires HTTPS or localhost. Enter the barcode instead.");if(!navigator.mediaDevices?.getUserMedia)return scannerError("Camera access is unavailable. Enter the barcode instead.");if(!window.ZXingBrowser?.BrowserMultiFormatReader)return scannerError("The scanner could not load. Enter the barcode instead.");$("scanner-status").textContent="Requesting camera permission…";try{const reader=new window.ZXingBrowser.BrowserMultiFormatReader();state.scannerControls=await reader.decodeFromConstraints({audio:false,video:{facingMode:{ideal:"environment"}}},$("scanner-video"),(result,_error,controls)=>{if(result){const code=normalizeBarcode(result.getText());if(code&&code!==state.lastScan){state.lastScan=code;navigator.vibrate?.(60);try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();g.gain.value=.025;o.frequency.value=620;o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.06);}catch(_e){}controls.stop();stopScanner();dialog.close();checkProduct(code);}}});state.stream=$("scanner-video").srcObject;$("scanner-status").textContent="Camera active. Center the entire barcode and hold steady.";setupTorch();}catch(error){scannerError(error?.name==="NotAllowedError"?"Camera permission was denied. Allow it in browser settings or enter the barcode instead.":error?.name==="NotFoundError"?"No camera was found. Enter the barcode instead.":"The camera could not start. Try more light or enter the barcode instead.");}}
  function setupTorch(){const track=state.stream?.getVideoTracks?.()[0],caps=track?.getCapabilities?.();if(!caps?.torch)return;const b=$("torch-button");b.hidden=false;b.onclick=async()=>{const on=b.getAttribute("aria-pressed")!=="true";try{await track.applyConstraints({advanced:[{torch:on}]});b.setAttribute("aria-pressed",String(on));b.textContent=on?"Turn off flashlight":"Turn on flashlight";}catch(_e){b.hidden=true;}};}
  function scannerError(message){stopScanner();$("scanner-status").textContent=message;}
  function stopScanner(){if(state.scannerControls){state.scannerControls.stop();state.scannerControls=null;}const stream=state.stream||$("scanner-video")?.srcObject;stream?.getTracks().forEach(t=>t.stop());state.stream=null;if($("scanner-video"))$("scanner-video").srcObject=null;$("torch-button").hidden=true;}
  function closeScanner(){stopScanner();if($("scanner-dialog").open)$("scanner-dialog").close();$("scan-button").focus();}
  function bindEvents(){$("scan-button").addEventListener("click",()=>{state.meaningfulInteraction=true;startScanner();});$("manual-button").addEventListener("click",()=>{state.meaningfulInteraction=true;openManual();});$("scanner-close").addEventListener("click",closeScanner);$("scanner-stop").addEventListener("click",closeScanner);$("scanner-manual").addEventListener("click",()=>{closeScanner();openManual();});$("scanner-dialog").addEventListener("cancel",e=>{e.preventDefault();closeScanner();});$("barcode-form").addEventListener("submit",e=>{e.preventDefault();submitBarcode();});$("continue-invalid").addEventListener("click",()=>submitBarcode(true));$("confirm-product").addEventListener("click",continueConfirmedProduct);$("reject-product").addEventListener("click",()=>{$("correction-actions").hidden=false;});$("correction-manual").addEventListener("click",()=>{resetCheck(false);openManual();});$("correction-scan").addEventListener("click",startScanner);$("direct-check").addEventListener("click",continueConfirmedProduct);window.addEventListener("pagehide",stopScanner);document.addEventListener("visibilitychange",()=>{if(document.hidden)stopScanner();});}
  window.addEventListener("beforeinstallprompt",event=>{event.preventDefault();state.installEvent=event;maybeShowInstall();});
  window.addEventListener("appinstalled",()=>{$("install-prompt").hidden=true;state.installEvent=null;});
  $("install-app")?.addEventListener("click",async()=>{if(!state.installEvent)return;await state.installEvent.prompt();await state.installEvent.userChoice;state.installEvent=null;$("install-prompt").hidden=true;});
  $("dismiss-install")?.addEventListener("click",()=>{state.installDismissed=true;$("install-prompt").hidden=true;});
  $("clear-session")?.addEventListener("click",()=>{state.history=[];renderHistory();});
  window.RecallCheck = Object.freeze({ normalizeBarcode, generateGtinVariants, validateCheckDigit, normalizeText, normalizeBrand, normalizePackageSize, exactCodeMatch, productNameTokenComparison, recallLifecycle, scoreRecall, classifyResult, lotCodeMatches, validateRecallData, dataAgeDays, isRecallDataUsable, identifyProductWithOpenFoodFacts, safeFeedbackContext, buildFeedbackPayload, feedbackMailto, feedbackMode, validFeedbackEndpoint, configureFeedback });
  $("copyright-year").textContent=new Date().getFullYear(); bindEvents(); loadData(); if ("serviceWorker" in navigator) navigator.serviceWorker.register("./sw.js").catch(() => {});
})();
