(() => {
  "use strict";
  const frame = document.getElementById("app");
  const list = document.getElementById("tests");
  let passed = 0, failed = 0;
  function report(name, ok, detail = "") { const item=document.createElement("li"); item.textContent=`${ok?"PASS":"FAIL"}: ${name}${detail?` — ${detail}`:""}`; item.style.color=ok?"#17613f":"#a1282f"; list.append(item); ok?passed++:failed++; }
  function assert(name, condition) { report(name, Boolean(condition)); }
  frame.addEventListener("load", async () => {
    const api=frame.contentWindow.RecallCheck, doc=frame.contentDocument;
    const recall=(overrides={})=>({id:"test",agency:"FDA",status:"ongoing",lifecycle:{state:"active",isActionable:true,sourceStatus:"Ongoing",terminationDate:""},recallDate:"2025-07-12",upcs:[],gtins:[],brandNames:[],productNames:[],packageSizes:[],lotCodes:[],dateCodes:[],...overrides});
    const product=(overrides={})=>({code:"012345678905",product_name:"",brands:"",quantity:"",...overrides});
    assert("Consumer-first heading",doc.querySelector("main h1")?.textContent==="Check a food product");
    assert("RecallCheck remains dominant with ITSBAD maker branding",doc.querySelector(".brand strong")?.textContent==="RecallCheck"&&doc.querySelector(".brand small")?.textContent.includes("ITSBAD LLC"));
    assert("ITSBAD LLC About content",doc.querySelector("#about")?.textContent.includes("About ITSBAD LLC"));
    assert("Footer ownership and independent disclaimer",doc.querySelector("footer")?.textContent.includes("product of ITSBAD LLC")&&doc.querySelector("footer")?.textContent.includes("independent ITSBAD LLC product"));
    assert("Dynamic copyright",doc.querySelector("#copyright-year")?.textContent===String(new Date().getFullYear()));
    assert("Feedback hidden before a completed result",!doc.querySelector(".feedback"));
    assert("Demo is secondary and fictional",doc.querySelector(".demo")?.textContent.includes("Fictional examples"));
    assert("Recall-only progress has exactly three steps",doc.querySelectorAll("#lookup-progress li").length===3&&doc.querySelector("#progress-product")?.textContent==="Product identified");
    assert("No consumer package-date controls or result cards",!["package-date-check","printed-date-dialog","progress-date"].some(id=>doc.getElementById(id))&&!doc.querySelector('[name="date-label"]'));
    assert("UPC normalization",api.normalizeBarcode("0123-456 78905")==="012345678905");
    const active=recall({upcs:["012345678905"]});
    assert("Active exact barcode match",api.classifyResult(product(),[active]).status==="confirmed_current_recall");
    const equivalent=recall({gtins:["00012345678905"]});
    const equivalentResult=api.classifyResult(product(),[equivalent]);
    assert("Active equivalent GTIN match",equivalentResult.status==="confirmed_current_recall"&&equivalentResult.equivalentBarcode);
    for(const state of ["terminated","closed"]){const result=api.classifyResult(product(),[recall({status:state,lifecycle:{state,isActionable:false,sourceStatus:state,terminationDate:"2025-09-01"},upcs:["012345678905"]})]);assert(`${state} exact barcode is historical`,result.status==="historical_exact_match");}
    const unknown=api.classifyResult(product(),[recall({status:"",lifecycle:{state:"unknown",isActionable:false,sourceStatus:"",terminationDate:""},upcs:["012345678905"]})]);
    assert("Unknown lifecycle exact match needs manual review",unknown.status==="current_recall_manual_review");
    assert("Old officially active recall remains current",api.classifyResult(product(),[recall({recallDate:"2020-01-01",timeline:{recallDate:"2020-01-01",ageDaysAtRefresh:2400,isRecent:false},upcs:["012345678905"]})]).status==="confirmed_current_recall");
    assert("Recent terminated recall is historical",api.classifyResult(product(),[recall({lifecycle:{state:"terminated",isActionable:false,sourceStatus:"Terminated",terminationDate:""},upcs:["012345678905"]})]).status==="historical_exact_match");
    for(const word of ["eggs","milk"]){const result=api.classifyResult(product({product_name:word,brands:"Other",quantity:"12 oz"}),[recall({productNames:[word],packageSizes:["12 oz"]})]);assert(`Generic ${word} similarity is no current recall`,result.status==="no_matching_current_recall");}
    const historical=recall({lifecycle:{state:"closed",isActionable:false,sourceStatus:"Completed",terminationDate:""},brandNames:["Orchard Morning"],productNames:["Honey Granola"],packageSizes:["10 oz"]});
    const similar=api.classifyResult(product({product_name:"Honey Granola",brands:"Orchard Morning",quantity:"10 oz"}),[historical]);
    assert("Distinctive historical similarity is secondary",similar.status==="no_matching_current_recall"&&similar.historicalRecords.length===1);
    const activeExact=recall({id:"active",upcs:["012345678905"]});
    assert("Active exact outranks historical similarity",api.classifyResult(product({product_name:"Honey Granola",brands:"Orchard Morning",quantity:"10 oz"}),[historical,activeExact]).recall.id==="active");
    const historicalExact=recall({id:"old",lifecycle:{state:"closed",isActionable:false,sourceStatus:"Closed",terminationDate:""},upcs:["012345678905"]});
    assert("Historical exact outranks generic similarity",api.classifyResult(product({product_name:"eggs"}),[recall({productNames:["eggs"]}),historicalExact]).status==="historical_exact_match");
    assert("Package size alone cannot match",api.classifyResult(product({quantity:"10 oz"}),[recall({packageSizes:["10 oz"]})]).status==="no_matching_current_recall");
    assert("Brand alone cannot trigger current recall",api.classifyResult(product({brands:"Orchard Morning"}),[recall({brandNames:["Orchard Morning"]})]).status==="no_matching_current_recall");
    const legacy=recall({lifecycle:undefined,status:"completed",upcs:["012345678905"]});
    assert("Missing lifecycle is backward compatible",api.classifyResult(product(),[legacy]).status==="historical_exact_match");
    const restricted=recall({upcs:["012345678905"],lotCodes:["LOT-A"]});
    assert("Active lot restriction needs details",api.classifyResult(product(),[restricted]).status==="current_recall_details_required");
    const source=await fetch("app.js").then(r=>r.text());
    assert("No package-date state or feedback context",!["dateCheckUsed","dateInputMethod","dateResultCategory","dateResult","dateLabel"].some(field=>source.includes(field)));
    const worker=await fetch("sw.js").then(r=>r.text());
    assert("Removed date feature is not cached",!worker.includes("date-check.js")&&!worker.includes("printed-date"));
    assert("Feedback prompt and accessible controls implemented",source.includes("Was this result helpful or confusing?")&&source.includes('el("button",value[0]')&&source.includes('el("fieldset")'));
    assert("Helpful and confusing structured reasons",source.includes("Result was clear")&&source.includes("Recall seemed unrelated")&&source.includes("Current versus historical was unclear"));
    assert("Optional comment character limit",source.includes("comment.maxLength=750")&&source.includes("remaining"));
    const safe=api.buildFeedbackPayload("confusing","Recall seemed unrelated","  detail  ",{status:"historical_exact_match",isDemo:true,exactBarcode:true});
    assert("Feedback safe fields and Demo context",safe.feedback==="confusing"&&safe.comment==="detail"&&safe.classification==="historical"&&safe.isDemo===true);
    assert("Endpoint payload excludes product identifiers",!["barcode","code","product","productName","brand","recallTitle","lotCode","dateCode","packageCode"].some(k=>Object.hasOwn(safe,k))&&!JSON.stringify(safe).includes("012345678905"));
    api.configureFeedback({mode:"endpoint",endpoint:"https://example.invalid/feedback",email:"CONFIGURE_FEEDBACK_EMAIL"});
    assert("HTTPS endpoint mode",api.feedbackMode()==="endpoint");
    api.configureFeedback({mode:"email",endpoint:"",email:"feedback@example.invalid"});
    const mailto=api.feedbackMailto(safe);
    assert("Email fallback is safe",mailto.startsWith("mailto:")&&mailto.includes("RecallCheck%20feedback")&&!mailto.includes("012345678905"));
    api.configureFeedback({mode:"disabled",endpoint:"",email:"CONFIGURE_FEEDBACK_EMAIL"});
    assert("Disabled feedback mode",api.feedbackMode()==="disabled");
    assert("Endpoint failure, timeout, duplicate prevention, and reset paths",source.includes("Your feedback could not be sent.")&&source.includes("state.feedbackSubmitting||state.feedbackSubmitted")&&source.includes("controller.abort()")&&source.includes("state.feedbackOutcome=null"));
    assert("Focus management",source.includes("follow.focus()")&&source.includes("h.focus()")&&source.includes("retry.focus()"));
    assert("No unsafe innerHTML or analytics",!source.includes(".innerHTML")&&!/google-analytics|googletagmanager|hotjar|clarity|facebook\.net/i.test(source));
    assert("Current and historical UI language",source.includes("No matching current recall found")&&source.includes("Similar historical recall"));
    assert("Historical result has no danger styling",source.includes('historical_exact_match:["i","Historical recall record"')&&source.includes('terminated.\",\"neutral\"]'));
    assert("No-current result retains non-guarantee",source.includes("This is not a safety guarantee"));
    assert("Current package verification keeps critical primary state",source.includes('current_recall_details_required:{label:"Current recall"')&&source.includes("package-verification package-verification--warning"));
    assert("Semantic SVG icons are decorative",source.includes('setAttribute("aria-hidden","true")')&&source.includes('setAttribute("focusable","false")'));
    assert("Package choices cover all certainty outcomes",["My package matches","My package does not match","I cannot find the code"].every(x=>source.includes(x)));
    assert("Failure, partial, no-match, and historical tones differ",['tone:"failure"','tone:"warning"','tone:"neutral-result"','tone:"historical"'].every(x=>source.includes(x)));
    const missing=await api.identifyProductWithOpenFoodFacts("12345670",{demo:{product:null}});
    assert("Product-service failure permits direct path",missing===null&&api.classifyResult(product(),[active]).status==="confirmed_current_recall");
    assert("Safe DOM rendering",(()=>{const n=doc.createElement("p");n.textContent="<img src=x onerror=alert(1)>";return n.children.length===0;})());
    document.getElementById("summary").textContent=`${passed} passed, ${failed} failed`; document.getElementById("summary").className=failed?"field-error":"notice";
  });
})();
