(() => {
  'use strict';
  const STATUS_URL='data/source-status.json';
  const OFFICIAL={FDA:'https://www.fda.gov/safety/recalls-market-withdrawals-safety-alerts',USDA:'https://www.fsis.usda.gov/recalls'};
  let status=null;
  const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n};
  const parsed=v=>{const t=Date.parse(v||'');return Number.isFinite(t)?new Date(t):null};
  const fmt=(v,time=false)=>{const d=parsed(v);if(!d)return 'not available';return new Intl.DateTimeFormat('en-US',time?{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}:{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(d)};
  function state(agency){const s=status?.sources?.[agency]||{};const quality=String(s.qualityStatus||s.coverageStatus||'').toLowerCase();const healthy=Boolean(s.success===true&&s.current===true&&s.freshnessValidated===true&&quality==='current');const failed=s.success===false||['failed','unavailable'].includes(quality);return{agency,s,healthy,failed}}
  const allHealthy=()=>state('FDA').healthy&&state('USDA').healthy;
  function updateGlobal(){
    const notice=document.getElementById('data-notice');const footer=document.getElementById('footer-updated');
    const f=state('FDA'),u=state('USDA');
    if(notice){notice.textContent=allHealthy()?`FDA verified through ${fmt(f.s.newestRecallDate)} · USDA FSIS through ${fmt(u.s.newestRecallDate)}`:'Official-source coverage is incomplete';notice.classList.toggle('coverage-current',allHealthy());notice.classList.toggle('coverage-warning',!allHealthy())}
    if(footer)footer.textContent=`Official source status checked ${fmt(status?.checkedAt||status?.generatedAt,true)}. Newest verified records: FDA ${fmt(f.s.newestRecallDate)}; USDA FSIS ${fmt(u.s.newestRecallDate)}.`;
    const root=document.getElementById('data-status-content');if(root){root.querySelectorAll('[data-rc-source-status]').forEach(n=>n.remove());const box=el('div');box.dataset.rcSourceStatus='true';[['FDA',f],['USDA FSIS',u]].forEach(([label,x])=>{const p=el('p',`${label}: ${x.healthy?'current and freshness-verified':'coverage needs attention'} · newest verified record ${fmt(x.s.newestRecallDate)} · last successful retrieval ${fmt(x.s.lastSuccessfulUpdate,true)}`,x.healthy?'source-trust-line':'source-trust-line source-trust-line--warning');box.append(p)});root.prepend(box)}
  }
  function officialLink(agency,label){const a=el('a',label,'button button--secondary trust-source-link');a.href=OFFICIAL[agency];a.target='_blank';a.rel='noopener noreferrer';return a}
  function isNoMatch(result){const t=(result.querySelector('.result-heading')?.textContent||'').toLowerCase();return t.includes('no matching recall found')||t.includes('no match found')||t.includes('no current recall')}
  function degradeNoMatch(result){if(allHealthy()||!isNoMatch(result))return;const heading=result.querySelector('.result-heading'),label=result.querySelector('.result-label'),instruction=result.querySelector('.result-instruction');result.className=result.className.replace(/result--[^\s]+/g,'').trim()+' result--warning trust-result-degraded';if(label)label.textContent='PARTIAL CHECK';if(heading)heading.textContent='No match found in the records RecallCheck could verify';if(instruction)instruction.textContent='At least one official source is unavailable, stale, or not freshness-verified. This result does not prove the product is not recalled.';if(!result.querySelector('.trust-degraded-actions')){const actions=el('div',null,'result-actions trust-degraded-actions');[state('FDA'),state('USDA')].filter(x=>!x.healthy).forEach(x=>actions.append(officialLink(x.agency,`Verify with ${x.agency}`)));(result.querySelector('.result-summary')||result).append(actions)}}
  function productIdentityCaution(result){const text=(result.textContent||'').toLowerCase();if(!(text.includes('product information')||text.includes('name unavailable')||text.includes('could not identify')))return;if(result.querySelector('[data-identity-caution]'))return;const p=el('p','Product identity could not be confirmed from this barcode. Any recall result reflects barcode matching only; compare package details with the official notice.','about-check-health about-check-health--warning');p.dataset.identityCaution='true';(result.querySelector('.result-summary')||result).prepend(p)}
  function addAbout(result){if(result.querySelector('.about-check'))return;const details=el('details',null,'about-check');details.append(el('summary','About this check'));const body=el('div',null,'about-check-body');const facts=el('dl',null,'about-check-facts');const add=(k,v)=>{const row=el('div',null,'about-check-row');row.append(el('dt',k),el('dd',v));facts.append(row)};add('Sources checked','FDA food recalls and USDA FSIS recalls');add('Official sources last checked',fmt(status?.checkedAt||status?.generatedAt,true));add('FDA newest verified record',fmt(state('FDA').s.newestRecallDate));add('USDA newest verified record',fmt(state('USDA').s.newestRecallDate));body.append(facts,el('p',allHealthy()?'FDA and USDA source coverage was current and freshness-verified for this check.':'At least one official source could not be confirmed current and freshness-verified, so this check may be incomplete.',allHealthy()?'about-check-health':'about-check-health about-check-health--warning'));const tech=el('details',null,'about-check-technical');tech.append(el('summary','Verify with official sources'));const techBody=el('div',null,'about-check-technical-body');techBody.append(officialLink('FDA','Open FDA official recalls'),officialLink('USDA','Open USDA FSIS recalls'));tech.append(techBody);body.append(tech);details.append(body);const feedback=result.querySelector('.feedback');result.insertBefore(details,feedback||null)}
  function enhance(){const result=document.querySelector('#result-panel .result');if(!result||!status)return;degradeNoMatch(result);productIdentityCaution(result);addAbout(result)}
  function failure(){const notice=document.getElementById('data-notice');if(notice){notice.textContent='Source verification unavailable';notice.classList.add('coverage-warning')}const footer=document.getElementById('footer-updated');if(footer)footer.textContent='RecallCheck could not verify official source freshness. Confirm results with FDA and USDA FSIS.';const root=document.getElementById('data-status-content');if(root){const p=el('p','RecallCheck could not verify source freshness right now. Results may be incomplete; use the official FDA and USDA FSIS listings for confirmation.','field-error');root.replaceChildren(p)}}
  async function init(){try{const r=await fetch(STATUS_URL,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);status=await r.json();updateGlobal();enhance();const panel=document.getElementById('result-panel');if(panel)new MutationObserver(enhance).observe(panel,{childList:true,subtree:true})}catch(_){status=null;failure()}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
